package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// init.go scaffolds a report pack (docs/report-packs.md) into an ADOPTER repo:
// the generated CI workflow and the pin scaffold an adopter needs to obtain a
// committed QUALITY.md from the sha256-pinned release binary, WITHOUT building
// qualgen from source.
//
// This is the pack contract's criterion 2 ("generated, never a template the
// adopter copies") for qualgen, mirroring `statusgen init`. Two properties are
// load-bearing and asserted by init_test.go:
//
//   - The emitted workflow acquires qualgen through channel E ONLY — the
//     sha256-verified release binary named in .assay-versions — and names NO
//     path specific to the producing repository (no `qualgen/` source dir, no
//     `go build`, no `cd qualgen`). An adopter has no such source to build; that
//     build-from-source shape is the producing-repo self-host seam, which lives
//     in medici-finance/assay's OWN workflow, never in an adopter's.
//   - The committed view is single-writer: the pull-request half runs
//     `qualgen report --out .` (no --write) and discards to stdout; only the
//     push-to-main half sets QUALGEN_QUALITY_WRITER=ci and runs `--write`. A
//     `--write` with that env unset is refused by report.go from the other side,
//     so CI — not a filename — is the sole writer of docs/quality/QUALITY.md.
//
// init NEVER overwrites an existing file: each target is created only if absent,
// so running it in a repo that already pins statusgen fills the qualgen gaps
// without clobbering the existing .assay-versions.

// initFiles is the (path, body) scaffold set init lays down, in order.
func initFiles() []struct{ path, body string } {
	return []struct{ path, body string }{
		{".github/workflows/assay-qualgen.yml", initQualgenWorkflow},
		{".assay-versions", initQualgenAssayVersions},
	}
}

// runInit scaffolds the report pack into root, creating each target only if
// absent, then prints next steps. `--dry-run` previews every rendered file and
// writes nothing.
func runInit(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(stderr)
	root := fs.String("root", ".", "target repo root to scaffold the report pack into")
	dryRun := fs.Bool("dry-run", false, "preview every file that would be created and write nothing")
	if err := fs.Parse(args); err != nil {
		return 2
	}

	files := initFiles()

	if *dryRun {
		for _, f := range files {
			fmt.Fprintf(stdout, "would create  %s\n", f.path)
			fmt.Fprintln(stdout, "----------------------------------------")
			fmt.Fprint(stdout, f.body)
			fmt.Fprintln(stdout, "----------------------------------------")
		}
		return 0
	}

	var created, skipped []string
	for _, f := range files {
		abs := filepath.Join(*root, filepath.FromSlash(f.path))
		if _, err := os.Stat(abs); err == nil {
			skipped = append(skipped, f.path)
			continue
		} else if !os.IsNotExist(err) {
			fmt.Fprintln(stderr, "qualgen init:", err)
			return 1
		}
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			fmt.Fprintln(stderr, "qualgen init:", err)
			return 1
		}
		if err := os.WriteFile(abs, []byte(f.body), 0o644); err != nil {
			fmt.Fprintln(stderr, "qualgen init:", err)
			return 1
		}
		created = append(created, f.path)
	}

	for _, p := range created {
		fmt.Fprintf(stdout, "  created  %s\n", p)
	}
	for _, p := range skipped {
		fmt.Fprintf(stdout, "  exists   %s (unchanged)\n", p)
	}
	if len(created) == 0 {
		fmt.Fprintln(stdout, "\nNothing to create — the report pack is already scaffolded.")
	}
	// If .assay-versions already existed (a repo that pins another pack), the
	// qualgen pin line is NOT added for it — say so, so the adopter adds it
	// consciously rather than discovering a missing pin at the first CI run.
	for _, p := range skipped {
		if p == ".assay-versions" {
			fmt.Fprint(stdout, initQualgenExistingPinNote)
		}
	}
	fmt.Fprint(stdout, initQualgenNextSteps)
	return 0
}

// initQualgenWorkflow is the ADOPTER quality-report workflow. It is the
// single-writer, two-half shape (docs/report-packs.md, criterion 3), acquiring
// qualgen through channel E only — the sha256-pinned release binary named in
// .assay-versions. It builds NOTHING from source: an adopter has no qualgen tree
// to build, and building from source is the producing-repo self-host seam that
// lives only in medici-finance/assay's own workflow.
const initQualgenWorkflow = `# quality-report CI — the two-half single-writer shape for the qualgen report
# pack (medici-finance/assay docs/report-packs.md). The pull-request half runs
# ` + "`qualgen report --out .`" + ` and DISCARDS (stdout only); the push-to-main half runs
# ` + "`qualgen report --out . --write`" + ` and commits docs/quality/QUALITY.md. QUALITY.md
# is generated by this workflow on main and has a SINGLE writer: never commit it
# on a branch. ` + "`qualgen report`" + `'s own guard enforces this from the other side — a
# ` + "`--write`" + ` with QUALGEN_QUALITY_WRITER unset is refused — so the PR half omits
# ` + "`--write`" + ` and touches nothing.
#
# qualgen comes from ONE place — the sha256-pinned release binary named in
# .assay-versions (channel E), installed and hash-verified below. It is NOT built
# from source: an adopter has no qualgen tree, and a build-from-source would be
# the non-sanctioned channel the distribution model retires. Fill .assay-versions
# with a real tag + per-platform digest before the first run; the install step
# refuses rather than guesses on a placeholder/absent pin line.
name: quality-report
on:
  pull_request:
    paths:
      - "docs/quality/**"
      - "!docs/quality/QUALITY.md"
      - ".assay-versions"
      - ".github/workflows/assay-qualgen.yml"
  push:
    branches: [main]
    paths:
      - "docs/quality/**"
      - "!docs/quality/QUALITY.md"
      - ".assay-versions"
      - ".github/workflows/assay-qualgen.yml"
concurrency:
  group: quality-report-${{ github.ref }}
  cancel-in-progress: false
permissions:
  contents: read
jobs:
  render:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pinned qualgen (channel E — sha256-verified release binary)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          plat="$(uname -s | tr A-Z a-z)-$(uname -m | sed 's/^x86_64$/amd64/; s/^aarch64$/arm64/')"
          line="$(grep "^qualgen-$plat " .assay-versions || true)"
          if [ -z "$line" ]; then
            echo "::error::no .assay-versions pin for platform qualgen-$plat — refusing rather than guessing"
            exit 1
          fi
          tag="$(printf '%s' "$line" | awk '{print $2}')"
          sha="$(printf '%s' "$line" | awk '{print $3}')"
          gh release download "$tag" --repo medici-finance/assay --pattern "qualgen-$plat" -O /tmp/qualgen
          echo "${sha}  /tmp/qualgen" | shasum -a 256 -c -
          sudo install -m 0755 /tmp/qualgen /usr/local/bin/qualgen
      - name: Render QUALITY.md (discard — single-writer is the main-push job)
        run: |
          set -euo pipefail
          # No --write and QUALGEN_QUALITY_WRITER unset: renders to stdout and
          # discards. The committed QUALITY.md is never touched on a branch.
          qualgen report --out . > "${RUNNER_TEMP}/QUALITY.preview.md"
          echo "rendered QUALITY.md preview ($(wc -l < "${RUNNER_TEMP}/QUALITY.preview.md") lines) — discarded on a branch"
  regen:
    # QUALITY.md is generated on main only, never on a branch (single writer).
    # The [skip-qualgen-regen] guard stops this job re-firing on its own commit.
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip-qualgen-regen]') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pinned qualgen (channel E — sha256-verified release binary)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          plat="$(uname -s | tr A-Z a-z)-$(uname -m | sed 's/^x86_64$/amd64/; s/^aarch64$/arm64/')"
          line="$(grep "^qualgen-$plat " .assay-versions || true)"
          if [ -z "$line" ]; then
            echo "::error::no .assay-versions pin for platform qualgen-$plat — refusing rather than guessing"
            exit 1
          fi
          tag="$(printf '%s' "$line" | awk '{print $2}')"
          sha="$(printf '%s' "$line" | awk '{print $3}')"
          gh release download "$tag" --repo medici-finance/assay --pattern "qualgen-$plat" -O /tmp/qualgen
          echo "${sha}  /tmp/qualgen" | shasum -a 256 -c -
          sudo install -m 0755 /tmp/qualgen /usr/local/bin/qualgen
      - name: Regenerate QUALITY.md
        env:
          # The CI-writer authorization qualgen report requires to take the
          # committed-view --write path. Set NOWHERE else — a local shell does
          # not set it, so a local --write is refused.
          QUALGEN_QUALITY_WRITER: ci
        run: |
          set -euo pipefail
          qualgen report --out . --write
      - name: Commit QUALITY.md if it changed
        run: |
          set -euo pipefail
          git config user.name  'qualgen'
          git config user.email 'qualgen@users.noreply.github.com'
          git add docs/quality/QUALITY.md
          # BOOTSTRAP-SAFE GUARD: guard on git status --porcelain, NOT git diff
          # --quiet. git diff sees only TRACKED files, so on a repo with no
          # QUALITY.md yet the diff guard mis-fires and the first view is never
          # created; porcelain reports the new file.
          if [ -n "$(git status --porcelain -- docs/quality/QUALITY.md)" ]; then
            git commit -m 'chore(quality): regenerate QUALITY.md [skip-qualgen-regen]'
            git push
          fi
`

// initQualgenAssayVersions is a PLACEHOLDER pin file in the channel-E shape
// (qualgen-<platform> <tag> <sha256>). It is deliberately not a live pin: init
// is baked into the qualgen binary, so a hardcoded digest here would go stale
// every release. The adopter fills a real tag + per-platform digest once, from a
// release's checksums.txt; the install step refuses rather than guesses on a
// placeholder line, so a fresh repo cannot silently install an unpinned binary.
const initQualgenAssayVersions = `# qualgen pin for this repo's quality-report CI — channel E, the sha256-pinned
# release binary (medici-finance/assay docs/report-packs.md, docs/distribution.md).
# One line per platform you install on, in the form:
#
#     qualgen-<platform>  <tag>  <sha256>
#
# PLACEHOLDER — fill in a REAL release tag + per-platform sha256 before the first
# CI run. Pick the qualgen release you want to pin, download its checksums.txt
# from the medici-finance/assay releases, and replace each REPLACE_WITH_* token
# with the tag and the digest for that artifact. Match the FULL platform (os AND
# arch). Re-pin (never edit in place) on an upgrade so the bump shows in a diff.
# The install step refuses rather than guesses on an absent or placeholder line.
qualgen-darwin-arm64  REPLACE_WITH_TAG  REPLACE_WITH_SHA256_FROM_RELEASE_CHECKSUMS
qualgen-darwin-amd64  REPLACE_WITH_TAG  REPLACE_WITH_SHA256_FROM_RELEASE_CHECKSUMS
qualgen-linux-amd64   REPLACE_WITH_TAG  REPLACE_WITH_SHA256_FROM_RELEASE_CHECKSUMS
`

// initQualgenExistingPinNote is printed only when .assay-versions already
// existed (a repo pinning another pack), because init did not add the qualgen
// line to it — so the adopter adds it consciously rather than hitting a missing
// pin at the first CI run.
const initQualgenExistingPinNote = `
NOTE: .assay-versions already existed and was left unchanged — the qualgen pin
was NOT added. Add one line per platform you install on, then fill a real tag +
per-platform sha256 from the medici-finance/assay release's checksums.txt:

    qualgen-darwin-arm64  <tag>  <sha256>
    qualgen-darwin-amd64  <tag>  <sha256>
    qualgen-linux-amd64   <tag>  <sha256>
`

const initQualgenNextSteps = `
Scaffolded the qualgen report pack. Next:

  1. Fill .assay-versions: replace the REPLACE_WITH_TAG / REPLACE_WITH_SHA256 tokens
     with a real qualgen release tag + per-platform sha256 (from that release's
     checksums.txt on medici-finance/assay). CI installs the pinned binary and
     refuses on a placeholder line, so this is the one required bootstrap step.
  2. Commit .github/workflows/assay-qualgen.yml — the two-half single-writer CI.
  3. QUALITY.md has a SINGLE writer (main's CI): the push-to-main half regenerates
     docs/quality/QUALITY.md and commits it. Never commit QUALITY.md on a branch;
     a local 'qualgen report --out . --write' is refused (QUALGEN_QUALITY_WRITER
     is set only by CI).

qualgen is obtained ONLY as the sha256-pinned release binary — this pack builds
nothing from source. See medici-finance/assay docs/report-packs.md for the pack
contract.
`
