package untrustcorpus

import (
	"fmt"
	"regexp"
	"strings"
)

// inert.go — the defang denylist, asserted over GENERATED bytes.
//
// Inertness is a property of the assembled sample, not of the table: the table names
// codepoints, and the only way to know the decoded bytes carry no live host or real
// credential is to decode them and look. InertViolations does exactly that, and the
// GeneratedSamplesAreInert test runs it over every sample the generator produces.

// credShapes are credential prefixes that must never appear in a generated sample. A
// positive control proves a scanner CATCHES a credential; it must not BE one.
var credShapes = []string{"ghp_", "ghs_", "github_pat_"}

// urlHostRe pulls the host[:port] out of an http(s) URL occurring in the bytes.
var urlHostRe = regexp.MustCompile(`(?i)https?://([^/\s"')]+)`)

// inertHosts are the sanctioned defang sinks: loopback and the RFC 6761 reserved names
// that never resolve. Any other host in a generated sample is a live-callout violation.
var inertHosts = map[string]bool{
	"127.0.0.1": true,
	"localhost": true,
	"::1":       true,
	"[::1]":     true,
}

// reservedTLDs are the reserved suffixes (RFC 2606 / 6761) that guarantee a name cannot
// route to a real endpoint. A host ending in one of these is inert by definition.
var reservedTLDs = []string{".invalid", ".test", ".example", ".localhost"}

// InertViolations returns every reason the bytes are NOT inert. Empty means clean.
// It is deliberately conservative: an unrecognised host is a violation, so a future edit
// that introduces a real sink fails the check rather than slipping through.
func InertViolations(b []byte) []string {
	s := string(b)
	var v []string
	for _, c := range credShapes {
		if strings.Contains(s, c) {
			v = append(v, fmt.Sprintf("contains credential shape %q", c))
		}
	}
	for _, m := range urlHostRe.FindAllStringSubmatch(s, -1) {
		host := hostOnly(m[1])
		if !hostIsInert(host) {
			v = append(v, fmt.Sprintf("outbound URL to non-inert host %q", host))
		}
	}
	return v
}

// hostOnly strips a trailing :port from a host[:port] token, leaving a bracketed IPv6
// literal intact.
func hostOnly(hp string) string {
	if strings.HasPrefix(hp, "[") {
		if i := strings.Index(hp, "]"); i >= 0 {
			return hp[:i+1]
		}
		return hp
	}
	if i := strings.LastIndex(hp, ":"); i >= 0 {
		return hp[:i]
	}
	return hp
}

func hostIsInert(host string) bool {
	h := strings.ToLower(strings.TrimSpace(host))
	if inertHosts[h] {
		return true
	}
	for _, tld := range reservedTLDs {
		if strings.HasSuffix(h, tld) {
			return true
		}
	}
	return false
}
