package untrustcorpus

import (
	"bytes"
	"testing"
	"unicode/utf8"
)

const testRoot = "testdata"

// loadOrFail loads the shipped table or fails the test.
func loadOrFail(t *testing.T) []Sample {
	t.Helper()
	s, err := Load(testRoot)
	if err != nil {
		t.Fatalf("Load(%q): %v", testRoot, err)
	}
	if len(s) == 0 {
		t.Fatalf("Load(%q): no samples", testRoot)
	}
	return s
}

// TestReproducible pins the generator's ground truth. For every entry the generated bytes
// must hash to the sha256 the table records, and two generations in one process must be
// byte-identical. A drift here would move the ground truth under the scanner silently,
// which is exactly what the pin exists to catch.
func TestReproducible(t *testing.T) {
	first := loadOrFail(t)
	second := loadOrFail(t)

	if len(first) != len(second) {
		t.Fatalf("two loads returned different lengths: %d vs %d", len(first), len(second))
	}
	for i := range first {
		a, b := first[i], second[i]
		if a.ID != b.ID {
			t.Fatalf("entry %d id drift: %q vs %q", i, a.ID, b.ID)
		}
		if !bytes.Equal(a.Bytes, b.Bytes) {
			t.Errorf("%s: two generations in one process are not byte-identical", a.ID)
		}
		if got := Pin(a.Bytes); got != a.SHA256 {
			t.Errorf("%s: generated bytes hash to %s, table pins %s (drift)", a.ID, got, a.SHA256)
		}
	}
}

// TestReproducible_PerturbationIsCaught is the control FOR the pin: it proves the pin has
// teeth. If a single byte of a generated sample changes, the recorded sha256 must no
// longer match. Without this, TestReproducible could pass vacuously against a pin that
// discriminates nothing. This is the mutation the reproducibility guard carries as its
// own fail-first evidence.
func TestReproducible_PerturbationIsCaught(t *testing.T) {
	s := loadOrFail(t)
	orig := s[0].Bytes
	if len(orig) == 0 {
		t.Fatalf("%s: empty sample, cannot perturb", s[0].ID)
	}
	perturbed := append([]byte(nil), orig...)
	perturbed[0] ^= 0x01 // flip one bit of one byte

	if Pin(perturbed) == s[0].SHA256 {
		t.Fatalf("%s: pin did NOT change under a one-bit perturbation — the reproducibility check is toothless", s[0].ID)
	}
	// And the unperturbed bytes still match, so the discriminator is not just noise.
	if Pin(orig) != s[0].SHA256 {
		t.Fatalf("%s: unperturbed bytes do not match the pin", s[0].ID)
	}
}

// TestGeneratesInvisibleUnicode is the discriminator: row 5 proves the TABLE is clean
// (no invisible chars on disk); this proves the CONTROL is real — the injection-unicode
// entry must GENERATE bytes that actually contain Tag-block/zero-width/bidi codepoints. A
// corpus that only describes smuggling proves nothing.
func TestGeneratesInvisibleUnicode(t *testing.T) {
	samples := loadOrFail(t)
	var checked int
	for _, s := range samples {
		if s.Class != "injection-unicode" {
			continue
		}
		checked++
		if !containsInvisibleUnicode(s.Bytes) {
			t.Errorf("%s: class injection-unicode but generated bytes carry no Tag-block/zero-width/bidi codepoint", s.ID)
		}
		// The bytes must also still be valid UTF-8: an invalid encoding here would mean
		// the generator produced something no scanner could reliably decode.
		if !utf8.Valid(s.Bytes) {
			t.Errorf("%s: generated bytes are not valid UTF-8", s.ID)
		}
	}
	if checked == 0 {
		t.Fatalf("no injection-unicode entry in the corpus — the invisible-unicode control is missing")
	}
}

// containsInvisibleUnicode reports whether b carries any Unicode Tag-block codepoint
// (U+E0000..U+E007F) or a zero-width / bidi-override control codepoint.
func containsInvisibleUnicode(b []byte) bool {
	invisible := map[rune]bool{
		0x200B: true, // zero-width space
		0x200C: true, // zero-width non-joiner
		0x200D: true, // zero-width joiner
		0x2066: true, // left-to-right isolate
		0x2067: true, // right-to-left isolate
		0x202A: true, // left-to-right embedding
		0x202B: true, // right-to-left embedding
		0x202D: true, // left-to-right override
		0x202E: true, // right-to-left override
		0xFEFF: true, // zero-width no-break space / BOM
	}
	for _, r := range string(b) {
		if r >= 0xE0000 && r <= 0xE007F {
			return true
		}
		if invisible[r] {
			return true
		}
	}
	return false
}

// TestGeneratedSamplesAreInert asserts the defang denylist over every GENERATED sample:
// no live callout host, no ghp_/ghs_/github_pat_ shape, no non-loopback external host. It
// runs over the bytes the generator produced, never over the table, because inertness is
// a property of the decoded sample.
func TestGeneratedSamplesAreInert(t *testing.T) {
	for _, s := range loadOrFail(t) {
		if v := InertViolations(s.Bytes); len(v) != 0 {
			t.Errorf("%s: not inert: %v", s.ID, v)
		}
	}
}

// TestGeneratedSamplesAreInert_DetectsALiveHost is the control FOR the inertness check:
// a byte string carrying a real host and a credential shape MUST be reported non-inert.
// Without it the inertness assertion could pass vacuously.
func TestGeneratedSamplesAreInert_DetectsALiveHost(t *testing.T) {
	live := []byte(`POST https://collector.example-attacker.com/x ghp_` + "AAAABBBBCCCCDDDD")
	v := InertViolations(live)
	if len(v) < 2 {
		t.Fatalf("inertness check missed a live host and/or credential shape: %v", v)
	}
}

// TestCheckPasses proves the shipped corpus is structurally sound: every entry names an
// existing detector layer, carries a current pin, and no layer or entry is orphaned.
func TestCheckPasses(t *testing.T) {
	res := Check(loadOrFail(t))
	if !res.OK() {
		t.Fatalf("Check found problems in the shipped corpus:\n  %v", res.Problems)
	}
}

// TestCheck_CatchesOrphansAndStalePins is the control FOR Check: it must report a
// missing layer, an entry with no layer, an unknown layer, and a stale pin. Without this
// TestCheckPasses could pass against a Check that finds nothing.
func TestCheck_CatchesOrphansAndStalePins(t *testing.T) {
	// Only Layer A present -> B/D orphaned; plus an unknown-layer entry, a no-layer
	// entry, and a stale pin.
	samples := []Sample{
		{ID: "a-only", Class: "benign", Layer: "A", Bytes: []byte("x"), SHA256: Pin([]byte("x"))},
		{ID: "no-layer", Class: "benign", Layer: "", Bytes: []byte("y"), SHA256: Pin([]byte("y"))},
		{ID: "bad-layer", Class: "benign", Layer: "C", Bytes: []byte("z"), SHA256: Pin([]byte("z"))},
		{ID: "stale", Class: "benign", Layer: "A", Bytes: []byte("q"), SHA256: "deadbeef"},
	}
	res := Check(samples)
	if res.OK() {
		t.Fatalf("Check passed a corpus with an orphaned layer, a no-layer entry, an unknown layer, and a stale pin")
	}
	wantSubstr := []string{"B/D", "no-layer", "bad-layer", "stale"}
	joined := ""
	for _, p := range res.Problems {
		joined += p + "\n"
	}
	for _, w := range wantSubstr {
		if !bytes.Contains([]byte(joined), []byte(w)) {
			t.Errorf("Check did not report %q; got:\n%s", w, joined)
		}
	}
}

// TestLoadRejectsBadCodepoint proves the loader fails closed on a malformed table rather
// than silently skipping a row.
func TestLoadRejectsBadCodepoint(t *testing.T) {
	if _, err := parseCodepoint("U+D800"); err == nil {
		t.Errorf("parseCodepoint accepted a surrogate U+D800")
	}
	if _, err := parseCodepoint("0x41"); err == nil {
		t.Errorf("parseCodepoint accepted a non-U+ token")
	}
	if _, err := parseCodepoint("U+110000"); err == nil {
		t.Errorf("parseCodepoint accepted an out-of-range codepoint")
	}
	if r, err := parseCodepoint("U+E0001"); err != nil || r != 0xE0001 {
		t.Errorf("parseCodepoint(U+E0001) = %v, %v; want 0xE0001, nil", r, err)
	}
}
