// Package untrustcorpus loads the positive-control corpus for the untrusted-read
// sample corpus and deterministically assembles each entry's inert bytes at run time.
//
// WHY IT EXISTS. No layer in this stream may trust a clean report until it has
// demonstrated it FLAGS a known-bad sample: a green check over a disarmed control is
// worse than no check. This package is the shared positive-control library the
// deterministic scan (Layer A) and the no-egress sandbox (Layer B/D) prove themselves
// against.
//
// WHY A GENERATOR, NOT A FIXTURE FILE. The tree carries a CODEPOINT / DESCRIPTION table
// (testdata/corpus.yaml), never a decoded attack string. Each entry lists the codepoint
// sequence by value (e.g. U+E0001); this package assembles the UTF-8 bytes in memory at
// run time. Nothing committed to the repo is itself a payload, which is why the table can
// be authored and reviewed by eye where the decoded samples could not.
//
// REPRODUCIBILITY IS THE CONTRACT. Same table in, same bytes out, on every platform and
// every run: the assembler is a pure codepoint decoder with no clock, no randomness, no
// map-iteration order and no locale-dependent encoding. Each entry pins the SHA-256 of its
// generated bytes; the reproducibility test asserts it, so the ground truth under the
// scanner cannot drift silently.
//
// INERTNESS IS BY CONSTRUCTION. The assembler has no code path that can emit a live host
// or a real-shaped credential — it only decodes the codepoints the table names, and the
// table's authored shapes resolve every sink to example.invalid / a loopback address and
// every credential to a placeholder. The inertness test asserts this over the GENERATED
// bytes, not over the table.
package untrustcorpus

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

// CorpusFile is the fixed base name of the codepoint/description table within a root.
const CorpusFile = "corpus.yaml"

// DetectorLayers are the detector layers that exist in this stream under the #1933
// ruling: A is the deterministic scan (brief 03); B/D is the no-egress sandbox (brief 04).
// There is no model-read layer — the #1933 ruling removed it — so no entry may name one.
var DetectorLayers = []string{"A", "B/D"}

// Expectation is the deterministic-scan verdict an entry asserts.
type Expectation struct {
	// Scan is "flag" or "clean": what the deterministic scan (Layer A) must do with
	// the generated bytes.
	Scan string `yaml:"scan"`
	// Reason is the stable marker the scan reports; it lets a consumer assert not just
	// that a sample flagged but that it flagged for the expected fault class.
	Reason string `yaml:"reason"`
}

// entry is one row of the table as authored on disk.
type entry struct {
	ID          string      `yaml:"id"`
	Class       string      `yaml:"class"`
	Layer       string      `yaml:"layer"`
	Codepoints  []string    `yaml:"codepoints"`
	Description string      `yaml:"description"`
	Expect      Expectation `yaml:"expect"`
	SHA256      string      `yaml:"sha256"`
}

type table struct {
	Entries []entry `yaml:"entries"`
}

// Sample is one loaded positive control: the table's metadata plus the bytes the
// generator assembled and their SHA-256 pin. Consumers (the scan, the sandbox) iterate
// []Sample uniformly.
type Sample struct {
	ID     string
	Class  string
	Layer  string
	Bytes  []byte
	Expect Expectation
	// SHA256 is the pin recorded in the table for the generated bytes. It is NOT
	// recomputed here; Reproducible (the test) is what asserts sha256(Bytes) == SHA256.
	SHA256 string
}

// validClasses is the closed set the table's `class` field may take.
var validClasses = map[string]bool{
	"exfil-callout":        true,
	"injection-unicode":    true,
	"injection-imperative": true,
	"code-exec":            true,
	"install-hook":         true,
	"benign":               true,
}

// Load reads the table under dir and assembles every entry's inert bytes. The root is a
// parameter, never hardcoded, so 03 and 04 can point Load at the same table from their own
// config. Load fails closed: a malformed table, an unparsable codepoint, or a structurally
// invalid entry is an error, never a silently skipped row.
func Load(dir string) ([]Sample, error) {
	path := filepath.Join(dir, CorpusFile)
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read corpus table %s: %w", path, err)
	}
	var t table
	if err := yaml.Unmarshal(raw, &t); err != nil {
		return nil, fmt.Errorf("parse corpus table %s: %w", path, err)
	}
	if len(t.Entries) == 0 {
		return nil, fmt.Errorf("corpus table %s has no entries", path)
	}
	samples := make([]Sample, 0, len(t.Entries))
	seen := map[string]bool{}
	for i, e := range t.Entries {
		where := fmt.Sprintf("%s entry #%d", path, i+1)
		if e.ID == "" {
			return nil, fmt.Errorf("%s: empty id", where)
		}
		if seen[e.ID] {
			return nil, fmt.Errorf("%s: duplicate id %q", where, e.ID)
		}
		seen[e.ID] = true
		if !validClasses[e.Class] {
			return nil, fmt.Errorf("%s (%s): unknown class %q", where, e.ID, e.Class)
		}
		b, err := assemble(e.Codepoints)
		if err != nil {
			return nil, fmt.Errorf("%s (%s): %w", where, e.ID, err)
		}
		samples = append(samples, Sample{
			ID:     e.ID,
			Class:  e.Class,
			Layer:  e.Layer,
			Bytes:  b,
			Expect: e.Expect,
			SHA256: e.SHA256,
		})
	}
	return samples, nil
}

// assemble decodes an ordered codepoint sequence into UTF-8 bytes. This is the ONE place
// bytes are produced, and it is deliberately total and pure: every token must be a
// "U+" hex codepoint, decoded to a rune and appended in order. There is no branch that can
// introduce a clock, randomness, map-iteration order, or a host/credential literal — the
// only bytes that can appear are the ones the table names by value.
func assemble(codepoints []string) ([]byte, error) {
	var sb strings.Builder
	for _, tok := range codepoints {
		r, err := parseCodepoint(tok)
		if err != nil {
			return nil, err
		}
		sb.WriteRune(r)
	}
	return []byte(sb.String()), nil
}

// parseCodepoint parses a single "U+XXXX" token (case-insensitive, 1..6 hex digits) into a
// rune, rejecting anything that is not a scalar value that round-trips through UTF-8.
func parseCodepoint(tok string) (rune, error) {
	t := strings.TrimSpace(tok)
	if len(t) < 3 || (t[0] != 'U' && t[0] != 'u') || t[1] != '+' {
		return 0, fmt.Errorf("codepoint %q is not in U+XXXX form", tok)
	}
	hexPart := t[2:]
	if len(hexPart) < 1 || len(hexPart) > 6 {
		return 0, fmt.Errorf("codepoint %q has %d hex digits (want 1..6)", tok, len(hexPart))
	}
	v, err := strconv.ParseUint(hexPart, 16, 32)
	if err != nil {
		return 0, fmt.Errorf("codepoint %q is not hex: %w", tok, err)
	}
	r := rune(v)
	// Reject surrogates and out-of-range values: they do not encode to valid UTF-8 and
	// would make the generator non-deterministic across encoders.
	if v > 0x10FFFF || (v >= 0xD800 && v <= 0xDFFF) {
		return 0, fmt.Errorf("codepoint %q is not a Unicode scalar value", tok)
	}
	return r, nil
}

// Pin computes the SHA-256 hex of b — the value the table records for a generated sample.
func Pin(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

// CheckResult reports the outcome of Check.
type CheckResult struct {
	Problems []string
}

// OK reports whether the corpus passed every structural check.
func (r CheckResult) OK() bool { return len(r.Problems) == 0 }

// Check validates the corpus structurally, the way `untrustcorpus check` and the
// stream's CI need it validated:
//   - every entry names a detector layer that exists in this stream (A or B/D);
//   - no entry names a model-read layer (the #1933 ruling removed it);
//   - every entry carries a current sha256 (present, and equal to the pin over its
//     generated bytes);
//   - no layer is orphaned (a layer named by no entry) and no entry is orphaned (an
//     entry naming no layer).
//
// It returns the collected problems rather than the first one, so a single run names
// everything that must be fixed.
func Check(samples []Sample) CheckResult {
	var res CheckResult
	named := map[string]bool{}
	for _, s := range samples {
		if s.Layer == "" {
			res.Problems = append(res.Problems, fmt.Sprintf("%s: entry names no detector layer", s.ID))
			continue
		}
		if !layerExists(s.Layer) {
			res.Problems = append(res.Problems, fmt.Sprintf("%s: layer %q is not a detector layer in this stream (want one of %s)", s.ID, s.Layer, strings.Join(DetectorLayers, ", ")))
			continue
		}
		named[s.Layer] = true
		if s.SHA256 == "" {
			res.Problems = append(res.Problems, fmt.Sprintf("%s: no sha256 pin", s.ID))
		} else if got := Pin(s.Bytes); got != s.SHA256 {
			res.Problems = append(res.Problems, fmt.Sprintf("%s: sha256 pin stale (table %s, generated %s)", s.ID, s.SHA256, got))
		}
	}
	// A layer with no entry has no proof it sees its own fault class.
	for _, l := range DetectorLayers {
		if !named[l] {
			res.Problems = append(res.Problems, fmt.Sprintf("layer %q is orphaned: no entry is a positive control for it", l))
		}
	}
	sort.Strings(res.Problems)
	return res
}

func layerExists(l string) bool {
	for _, d := range DetectorLayers {
		if d == l {
			return true
		}
	}
	return false
}
