#!/usr/bin/env bash
# stamp-plugin-version.sh — keep the plugin manifest version in step with the umbrella tag (#789).
#
# WHY. Claude Code keys its plugin cache by `plugin.json`'s `version`. Every umbrella tag through
# v1.0.6 shipped `"version": "1.0.0"`, so an adopter who already had 1.0.0 cached never received a
# later tag's content: `claude plugin update` is a no-op at an unchanged version, and only a fresh
# `plugin install` rewrites the cache. The version string is therefore PART OF THE RELEASE, and this
# script is the one place it is written — by the release workflow at cut time, never by hand.
#
# WHAT `stamp <vX.Y.Z>` WRITES, all to the same X.Y.Z:
#
#   plugins/assay/.claude-plugin/plugin.json         `version`         the hand-edited source
#   .claude-plugin/marketplace.json                  the `assay` entry's `version`
#   plugins/assay/paired-versions.yaml               `plugin:`         (check-paired-versions.sh A)
#   plugins/assay/.codex-plugin/plugin.json          `version`         GENERATED by harnessgen codex
#   plugins/assay/hooks/resident-rules.payload.txt   Header version    GENERATED by harnessgen resident
#   plugins/assay/codex/AGENTS-assay.md              Header version    GENERATED by harnessgen resident
#   plugins/assay/cursor/assay.mdc                   Header version    GENERATED by harnessgen cursor
#
# The four generated artifacts derive their version from plugin.json (#730). Rewriting the version
# token in place is byte-identical to regenerating — the release workflow PROVES that after every
# stamp with `harnessgen resident|codex|cursor --check` — and needs no Go on the caller's side, so
# the changelog-roll job (no toolchain) can run the same stamp.
#
# VERBS
#   stamp <vX.Y.Z> [--root DIR]   rewrite every file above to X.Y.Z. Idempotent.
#   check <vX.Y.Z> [--root DIR]   exit 1 unless every file above already carries X.Y.Z.
#   gate  --tag <vX.Y.Z> --prev <ref> [--have X.Y.Z] [--root DIR]
#                                 the release gate. Refuses (exit 1) when
#                                   (a) `git diff --quiet <ref> HEAD -- plugins/assay/` is non-empty
#                                       AND the manifest version is unchanged from <ref>'s, or
#                                   (b) the version the tagged tree carries is not X.Y.Z.
#                                 --have names the version the tagged tree WILL carry (the dispatch
#                                 path stamps before tagging); default: the working tree's
#                                 plugin.json. An empty --prev means "no previous tag": (a) is
#                                 skipped and said so, (b) still applies.
#   paths                         print the files `stamp` writes, one per line (for a path-scoped
#                                 `git add`).
#
# EXIT CODES   0 ok · 1 refused / drift · 2 usage or could-not-check.
# THREE-STATE: a file that cannot be read, or that carries no version token to rewrite, is a
# FAILURE (2), never a quiet pass — a stamp that silently skipped a file is exactly the drift
# that shipped adopters a stale plugin.
#
# No network, no jq, no Go. Run:
#   bash plugins/assay/scripts/stamp-plugin-version.sh stamp v1.2.3
#   bash plugins/assay/scripts/stamp-plugin-version.sh check v1.2.3
# Suite: stamp-plugin-version.test.sh (globbed by ci.yml's `plugin-shell-suites` job).
set -uo pipefail

version_re='^v[0-9]+\.[0-9]+\.[0-9]+$'
bare_re='^[0-9]+\.[0-9]+\.[0-9]+$'

# The seven files, relative to the root. Order is the order `paths` prints them.
MANIFEST='plugins/assay/.claude-plugin/plugin.json'
MARKETPLACE='.claude-plugin/marketplace.json'
PAIRED='plugins/assay/paired-versions.yaml'
CODEX_MANIFEST='plugins/assay/.codex-plugin/plugin.json'
HEADER_FILES=(
  'plugins/assay/hooks/resident-rules.payload.txt'
  'plugins/assay/codex/AGENTS-assay.md'
  'plugins/assay/cursor/assay.mdc'
)
ALL_PATHS=("$MANIFEST" "$MARKETPLACE" "$PAIRED" "$CODEX_MANIFEST" "${HEADER_FILES[@]}")

usage() {
  sed -n '2,50p' "$0" | sed 's/^# \{0,1\}//' >&2
  exit 2
}
die_usage() { printf 'FAIL %s\n' "$1" >&2; exit 2; }
cnc()       { printf 'FAIL could-not-check: %s\n' "$1" >&2; exit 2; }

# ------------------------------------------------------------------ readers
# Each prints the version a file carries, or nothing when the token is absent.

# `"version": "X.Y.Z"` — first occurrence (plugin.json and the Codex manifest carry exactly one).
json_version() { sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$1" | head -1; }

# `plugin: "X.Y.Z"` — the top-level pairing key, quotes optional.
paired_version() { sed -n 's/^plugin:[[:space:]]*"\{0,1\}\([^"[:space:]]*\)"\{0,1\}[[:space:]]*$/\1/p' "$1" | head -1; }

# `(assay plugin vX.Y.Z)` — the Header line the generators resolve {{VERSION}} into.
header_version() { sed -n 's/.*(assay plugin v\([^)]*\)).*/\1/p' "$1" | head -1; }

# The `assay` entry's version inside the marketplace catalog's `plugins` array. The entry is
# located by its `"name": "assay"` line after `"plugins"`; the first `"version"` line that
# follows, before the next entry opens (a bare `{` line), is the one. Other entries are left
# untouched, so a second plugin in the catalog is never stamped by accident.
marketplace_awk() {
  # $1 = mode (get|set), $2 = version for set
  awk -v mode="$1" -v ver="${2:-}" '
    /"plugins"[[:space:]]*:/ { inplugins = 1 }
    inplugins && /^[[:space:]]*\{[[:space:]]*$/ { inassay = 0 }
    inplugins && /"name"[[:space:]]*:[[:space:]]*"assay"[[:space:]]*,?[[:space:]]*$/ { inassay = 1 }
    inassay && !done && /"version"[[:space:]]*:/ {
      if (mode == "get") {
        v = $0; sub(/.*"version"[[:space:]]*:[[:space:]]*"/, "", v); sub(/".*/, "", v); print v
      } else {
        sub(/"version"[[:space:]]*:[[:space:]]*"[^"]*"/, "\"version\": \"" ver "\"")
      }
      done = 1
    }
    mode == "set" { print }
    END { if (!done) exit 3 }
  '
}
marketplace_version() { marketplace_awk get < "$1"; }

# ------------------------------------------------------------------ writers
# Portable in-place edit: write a sibling temp file, then mv over the original (no `sed -i`
# dialect dependence between GNU and BSD sed).
rewrite() {
  # $1 = file, rest = the filter command
  local file="$1"; shift
  local tmp="${file}.stamp.$$"
  if ! "$@" < "$file" > "$tmp"; then rm -f "$tmp"; return 1; fi
  mv "$tmp" "$file"
}

set_json_version() { rewrite "$1" sed "1,/\"version\"[[:space:]]*:/ s/\"version\"[[:space:]]*:[[:space:]]*\"[^\"]*\"/\"version\": \"$2\"/"; }
set_paired_version() { rewrite "$1" sed "s/^plugin:[[:space:]]*\"\{0,1\}[^\"[:space:]]*\"\{0,1\}[[:space:]]*\$/plugin: \"$2\"/"; }
set_header_version() { rewrite "$1" sed "s/(assay plugin v[^)]*)/(assay plugin v$2)/"; }
set_marketplace_version() { rewrite "$1" marketplace_awk set "$2"; }

# ------------------------------------------------------------------ verbs
parse_root() {
  ROOT=""
  REST=()
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --root)
        ROOT="${2:-}"; [[ -n "$ROOT" ]] || die_usage '--root needs a directory'
        shift 2 ;;
      *) REST+=("$1"); shift ;;
    esac
  done
  if [[ -z "$ROOT" ]]; then
    # Default: the repo root three levels above this script (plugins/assay/scripts/ -> repo root).
    ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
  fi
}

require_readable() {
  local f
  for f in "${ALL_PATHS[@]}"; do
    [[ -r "$ROOT/$f" ]] || cnc "cannot read $f under $ROOT"
  done
}

# verify <X.Y.Z> — prints one line per file; returns 1 on any mismatch, 2 on any missing token.
verify() {
  local want="$1" rc=0 f have
  local -a rows
  rows=(
    "$MANIFEST|$(json_version "$ROOT/$MANIFEST")"
    "$MARKETPLACE|$(marketplace_version "$ROOT/$MARKETPLACE")"
    "$PAIRED|$(paired_version "$ROOT/$PAIRED")"
    "$CODEX_MANIFEST|$(json_version "$ROOT/$CODEX_MANIFEST")"
  )
  for f in "${HEADER_FILES[@]}"; do rows+=("$f|$(header_version "$ROOT/$f")"); done
  local row
  for row in "${rows[@]}"; do
    f="${row%%|*}"; have="${row#*|}"
    if [[ -z "$have" ]]; then
      printf 'FAIL %s carries no version token — could-not-check\n' "$f" >&2; rc=2
    elif [[ "$have" != "$want" ]]; then
      printf 'FAIL %s carries %s, want %s\n' "$f" "$have" "$want" >&2; [[ "$rc" -eq 2 ]] || rc=1
    else
      printf 'ok   %s carries %s\n' "$f" "$have"
    fi
  done
  return "$rc"
}

cmd_paths() { printf '%s\n' "${ALL_PATHS[@]}"; }

cmd_stamp() {
  parse_root "$@"
  [[ "${#REST[@]}" -eq 1 ]] || die_usage 'stamp takes exactly one <vX.Y.Z>'
  local tag="${REST[0]}"
  [[ "$tag" =~ $version_re ]] || die_usage "version must be vMAJOR.MINOR.PATCH (got '$tag')"
  local ver="${tag#v}"
  require_readable
  # Every file must carry a token to rewrite BEFORE anything is written, so a half-stamped tree
  # cannot result from a file that lost its token.
  local f
  [[ -n "$(json_version "$ROOT/$MANIFEST")" ]]           || cnc "$MANIFEST has no \`version\` field"
  [[ -n "$(marketplace_version "$ROOT/$MARKETPLACE")" ]] || cnc "$MARKETPLACE has no \`assay\` plugin entry with a \`version\`"
  [[ -n "$(paired_version "$ROOT/$PAIRED")" ]]           || cnc "$PAIRED has no top-level \`plugin:\` key"
  [[ -n "$(json_version "$ROOT/$CODEX_MANIFEST")" ]]     || cnc "$CODEX_MANIFEST has no \`version\` field"
  for f in "${HEADER_FILES[@]}"; do
    [[ -n "$(header_version "$ROOT/$f")" ]] || cnc "$f has no \`(assay plugin vX.Y.Z)\` Header token"
  done

  set_json_version "$ROOT/$MANIFEST" "$ver"              || cnc "rewriting $MANIFEST"
  set_marketplace_version "$ROOT/$MARKETPLACE" "$ver"    || cnc "rewriting $MARKETPLACE"
  set_paired_version "$ROOT/$PAIRED" "$ver"              || cnc "rewriting $PAIRED"
  set_json_version "$ROOT/$CODEX_MANIFEST" "$ver"        || cnc "rewriting $CODEX_MANIFEST"
  for f in "${HEADER_FILES[@]}"; do
    set_header_version "$ROOT/$f" "$ver"                 || cnc "rewriting $f"
  done

  # Read back what was written — the stamp is only done when the check verb would pass.
  if ! verify "$ver"; then
    printf 'stamp-plugin-version: FAILED to stamp %s\n' "$ver" >&2; exit 2
  fi
  printf 'stamp-plugin-version: stamped %s\n' "$ver"
}

cmd_check() {
  parse_root "$@"
  [[ "${#REST[@]}" -eq 1 ]] || die_usage 'check takes exactly one <vX.Y.Z>'
  local tag="${REST[0]}"
  [[ "$tag" =~ $version_re ]] || die_usage "version must be vMAJOR.MINOR.PATCH (got '$tag')"
  require_readable
  local rc=0
  verify "${tag#v}" || rc=$?
  if [[ "$rc" -ne 0 ]]; then
    printf 'stamp-plugin-version: tree does not carry plugin version %s\n' "${tag#v}" >&2; exit "$rc"
  fi
  printf 'stamp-plugin-version: OK — every file carries %s\n' "${tag#v}"
}

cmd_gate() {
  local tag="" prev="" have="" prev_set=0
  local -a pass
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --tag)  tag="${2:-}";  shift 2 ;;
      --prev) prev="${2:-}"; prev_set=1; shift 2 ;;
      --have) have="${2:-}"; shift 2 ;;
      *) pass+=("$1"); shift ;;
    esac
  done
  parse_root "${pass[@]+"${pass[@]}"}"
  [[ "${#REST[@]}" -eq 0 ]] || die_usage "gate: unknown argument: ${REST[0]}"
  [[ "$tag" =~ $version_re ]] || die_usage "gate --tag must be vMAJOR.MINOR.PATCH (got '$tag')"
  [[ "$prev_set" -eq 1 ]] || die_usage 'gate needs --prev <ref> (pass an empty value for "no previous tag")'
  local want="${tag#v}"
  [[ -r "$ROOT/$MANIFEST" ]] || cnc "cannot read $MANIFEST under $ROOT"
  if [[ -z "$have" ]]; then
    have=$(json_version "$ROOT/$MANIFEST")
    [[ -n "$have" ]] || cnc "$MANIFEST has no \`version\` field"
  fi
  [[ "$have" =~ $bare_re ]] || die_usage "gate: the manifest version must be MAJOR.MINOR.PATCH (got '$have')"

  local fail=0
  if [[ -z "$prev" ]]; then
    printf 'note no previous umbrella tag — the plugins/assay change check has nothing to compare against and is skipped\n'
  else
    # The previous tag's manifest version, read from ITS tree.
    local prev_manifest prev_have
    if ! prev_manifest=$(git -C "$ROOT" show "${prev}:${MANIFEST}" 2>/dev/null); then
      cnc "cannot read ${MANIFEST} at ${prev} (is the ref fetched?)"
    fi
    prev_have=$(printf '%s\n' "$prev_manifest" | sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
    [[ -n "$prev_have" ]] || cnc "${MANIFEST} at ${prev} has no \`version\` field"

    # Did plugins/assay/ change between the previous tag and the tree being tagged?
    local changed
    git -C "$ROOT" diff --quiet "$prev" HEAD -- plugins/assay/ 2>/dev/null
    case "$?" in
      0) changed=no ;;
      1) changed=yes ;;
      *) cnc "git diff ${prev}..HEAD -- plugins/assay/ did not answer (is ${prev} fetched?)" ;;
    esac

    if [[ "$changed" = yes && "$have" = "$prev_have" ]]; then
      printf 'FAIL plugins/assay/ differs from %s but the plugin manifest version is unchanged (%s) — a tag whose plugin content moved without its version moving is an update adopters never receive (Claude Code keys the plugin cache on that version)\n' "$prev" "$have" >&2
      fail=1
    else
      printf 'ok   plugins/assay/ %s since %s; manifest version %s -> %s\n' \
        "$([[ "$changed" = yes ]] && echo changed || echo unchanged)" "$prev" "$prev_have" "$have"
    fi
  fi

  if [[ "$have" != "$want" ]]; then
    printf 'FAIL the tagged tree carries plugin version %s but the tag is %s — the manifest version must equal the umbrella tag\n' "$have" "$tag" >&2
    fail=1
  else
    printf 'ok   manifest version %s == tag %s\n' "$have" "$tag"
  fi

  if [[ "$fail" -ne 0 ]]; then
    printf 'stamp-plugin-version gate: REFUSED %s\n' "$tag" >&2; exit 1
  fi
  printf 'stamp-plugin-version gate: OK %s\n' "$tag"
}

[[ $# -ge 1 ]] || usage
verb="$1"; shift
case "$verb" in
  stamp) cmd_stamp "$@" ;;
  check) cmd_check "$@" ;;
  gate)  cmd_gate "$@" ;;
  paths) cmd_paths ;;
  -h|--help) usage ;;
  *) die_usage "unknown verb: $verb (known: stamp, check, gate, paths)" ;;
esac
