package main

import (
	"io/fs"
	"path/filepath"
	"sort"
	"strings"
)

// regen.go — the compiled-in carve-outs. Both lists below are the boundary of the
// desk's authority, so both are CODE: widening either requires a diff, a review and a
// human merge. Neither is readable from a flag, an environment variable or a file in
// the target repo — a boundary the target repo could widen is not a boundary.

// regenerable is the set of paths whose merge conflict deskmerge may resolve, and the
// generator that resolves each. The resolution is NOT a merge: the file is regenerated
// from its declared source, so the output is whatever the source says and no hunk from
// either side survives by being chosen. That is what makes it transport rather than
// authorship — the derive-or-diff rule's one legitimate use for an auto-resolution.
//
// STATUS.md is the initial and, today, only member: it is machine-generated by
// statusgen from docs/streams/**, it changes on nearly every merge, and its conflicts
// carry no author's intent.
//
// Deliberately NOT here, though every one of them is tempting:
//   - docs/streams/*/README.md — the brief status tables. Hand-authored; a conflict
//     there is two people disagreeing about a brief's state.
//   - docs/brief-rules.md — the live proof of why. It carries DUPLICATE rule numbers 25
//     and 26 right now, because two briefs each authored into
//     the same numbering space in parallel and neither diff showed the other's numbers.
//     That collision produced NO conflict at all, so no auto-resolution would have been
//     invoked; adding the file to this list would only have widened the blast radius of
//     the next one.
//   - go.sum / lockfiles. Regenerable in principle, but the regenerated result depends
//     on the network and on resolution order, so "re-run the generator" is not a
//     deterministic function of the tree.
var regenerable = map[string]regenerator{
	"STATUS.md": {
		Tool: "statusgen",
		// Argv is run with cwd = the merge worktree root. statusgen rewrites
		// STATUS.md in place from docs/streams/**; --root . pins it to the worktree
		// and not to whatever tree the desk happens to be sitting in.
		Argv: []string{"--root", "."},
	},
}

// regenerator names the generator that owns a regenerable path.
type regenerator struct {
	Tool string
	Argv []string
}

// classifyConflicts splits a conflicted path set into (listed, unlisted).
//
// The caller refuses on ANY unlisted path — including the MIXED case, where some paths
// are listed and some are not. There is no partial resolution, and the reason is not
// squeamishness: resolving the listed half would produce a commit that is part
// transport and part abandoned merge, and the desk would then be the author of a tree
// nobody chose. Refusing whole is the only disposition that keeps "a desk merge
// introduces no reviewable content" true.
func classifyConflicts(paths []string) (listed, unlisted []string) {
	for _, p := range paths {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		if _, ok := regenerable[p]; ok {
			listed = append(listed, p)
			continue
		}
		unlisted = append(unlisted, p)
	}
	sort.Strings(listed)
	sort.Strings(unlisted)
	return listed, unlisted
}

// regenerableList renders the compiled-in list for a refusal message, so a caller
// reading "refused: conflicts outside the regenerable list" can see what the list IS
// without reading the source.
func regenerableList() string {
	out := make([]string, 0, len(regenerable))
	for p := range regenerable {
		out = append(out, p)
	}
	sort.Strings(out)
	return strings.Join(out, ", ")
}

// ---------------------------------------------------------------------------
// the merged-tree probe — deskmerge's ONLY detector for a semantic collision
// ---------------------------------------------------------------------------

// probeArgv is the compiled-in build command --probe runs in each discovered module.
//
// This is the answer — the only one deskmerge has — to the failure class a textual
// conflict check cannot see: two branches, each green on its own, invalid against each
// other. #912/#913 is the worked example: `emit()` in statusgen/emit.go grew an 8th
// parameter on main while another green PR still called it with 7 args. No conflict, two
// green PRs, red main. `go build` on the MERGED tree catches it; nothing short of
// building the merged tree does.
//
// It is compiled in rather than flag-supplied on purpose. A `--probe <cmd>` flag would
// make deskmerge an arbitrary-command runner that happens to also merge, and the caller
// of a desk tool is not always the person who wrote the argument.
//
// Its limits, stated rather than implied: it is a BUILD, not a test run (a test suite on
// a merged tree costs minutes, and a currency probe that costs minutes will not be run);
// and it is blind to every collision the compiler cannot see. The duplicate rule numbers
// 25/26 in docs/brief-rules.md are exactly that — a real semantic collision, in prose,
// that no probe here would report.
var probeArgv = []string{"go", "build", "./..."}

// probeStep is one command run in the merged worktree under --probe.
type probeStep struct {
	Dir  string // relative to the worktree root
	Argv []string
}

// probeTargets is the seam tests replace. Production binds it to discoverProbeTargets,
// which DERIVES the target set from the merged tree rather than from a table keyed by
// repo name.
//
// It was a table once, and the live smoke test is why it is not: keyed by repo, the map
// answered could-not-check for the repo the desk actually operates on, because the key
// named a sibling. A lookup table of repo names is also the wrong shape for a second
// reason — the repo set was deliberately moved OUT of this source tree into operator
// configuration, so re-introducing repo names here would ship them in every binary.
var probeTargets = discoverProbeTargets

// discoverProbeTargets finds the Go modules in the merged worktree that either side
// touched, and returns a build step for each.
//
// Scoped to TOUCHED modules on purpose: a semantic collision lives where one side
// changed a definition and the other a caller, and both are inside one module. Building
// modules nobody touched costs time and can only report pre-existing breakage, which is
// not this run's news. "Either side" rather than "both sides" is the deliberate
// over-approximation — cheap, and it cannot miss.
//
// An empty result is could-not-check, never clean: "this tree has no Go module I know
// how to build" and "this tree builds" are different statements, and only one of them
// is true.
func discoverProbeTargets(dir string, changed []string) []probeStep {
	mods := goModuleDirs(dir)
	if len(mods) == 0 {
		return nil
	}
	hit := map[string]bool{}
	for _, path := range changed {
		if best := owningModule(mods, path); best != "" {
			hit[best] = true
		}
	}
	out := make([]probeStep, 0, len(hit))
	for _, m := range mods {
		if hit[m] {
			out = append(out, probeStep{Dir: m, Argv: probeArgv})
		}
	}
	return out
}

// goModuleDirs lists directories under root that hold a go.mod, as slash-separated
// paths relative to root ("." for the root module), sorted. Vendored and dependency
// trees are skipped: they are not this branch's code and building them proves nothing
// about the merge.
func goModuleDirs(root string) []string {
	var out []string
	_ = filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil //nolint:nilerr // an unreadable subtree is skipped, not fatal
		}
		if d.IsDir() {
			switch d.Name() {
			case ".git", "vendor", "node_modules", "testdata":
				return filepath.SkipDir
			}
			return nil
		}
		if d.Name() != "go.mod" {
			return nil
		}
		rel, rerr := filepath.Rel(root, filepath.Dir(p))
		if rerr != nil {
			return nil
		}
		out = append(out, filepath.ToSlash(rel))
		return nil
	})
	sort.Strings(out)
	return out
}

// owningModule returns the LONGEST module path that contains file — the nearest
// enclosing go.mod, which is the module the Go toolchain would actually compile it in.
// Taking the shortest instead would attribute every nested module's files to the root
// module and build the wrong thing.
func owningModule(mods []string, file string) string {
	file = filepath.ToSlash(strings.TrimSpace(file))
	best := ""
	for _, m := range mods {
		if m == "." {
			if best == "" {
				best = "."
			}
			continue
		}
		if strings.HasPrefix(file, m+"/") && len(m) > len(best) {
			best = m
		}
	}
	return best
}
