package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// coverage_test.go — the evidence coverage rule (graph-execution/03). Top-level
// functions are named TestCoverage* so Verify row 1's `-run TestCoverage`
// selector counts them all.

// covWitnessRow renders one Evidence witness row exactly as verifyrun.go's own
// witness.row() would — generated by the SAME code coverage.go reads, never a
// hand-typed guess at the table format.
func covWitnessRow(id, command, state, tree string) string {
	exit := 0
	if state == stateFail {
		exit = 1
	}
	w := witness{
		ID: id, Command: command, State: state, Exit: exit,
		OutHash: "abc123def456", Date: "2026-09-25", Runner: "fixture-verifier", Tree: tree,
	}
	return w.row()
}

// coverageEvidenceTable wraps one or more witness/advice rows in the witness
// table header.
func coverageEvidenceTable(rows ...string) string {
	out := witnessHeader
	for _, r := range rows {
		out += "\n" + r
	}
	return out
}

// writeCoverageBrief writes a minimal, valid brief-v1 file (the same required-key
// shape testdata/autoflip's fixtures already use) with the given Verify/Evidence
// bodies, under dir/brief-<num>.md.
func writeCoverageBrief(t *testing.T, dir, num, streamName, verifyBody, evidenceBody string) {
	t.Helper()
	writeCoverageBriefWithFiles(t, dir, num, streamName, "", verifyBody, evidenceBody)
}

// writeCoverageBriefWithFiles is writeCoverageBrief plus an optional `## Context`
// `files:` line (filesLine is its inline value, e.g. "`src/impl.go`"; "" omits
// the Context section entirely) — the declared scope a witness speaks for
// (review finding F2, round 2).
func writeCoverageBriefWithFiles(t *testing.T, dir, num, streamName, filesLine, verifyBody, evidenceBody string) {
	t.Helper()
	context := ""
	if filesLine != "" {
		context = "## Context\nfiles: " + filesLine + "\n\n"
	}
	content := fmt.Sprintf(`---
brief: %s/%s
title: coverage fixture
wave: 0
depends: []
unblocks: []
effort: S
gate: model
risk: {regulatory: no, customer: no, irreversible: no, sensitive-data: no}
issues: []
schema: brief-v1
authored: 2026-09-25 by graph-execution/03 fixture
sources: ["fixture: graph-execution/03 coverage_test.go"]
---

# Brief %s — coverage fixture

%s## Verify
%s

## Evidence
<!-- contract comment -->

%s

## Review
Gate: model.
`, streamName, num, num, context, verifyBody, evidenceBody)
	if err := os.WriteFile(filepath.Join(dir, "brief-"+num+".md"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// mustCoverageStream returns a fresh temp root (deliberately NOT a git repo —
// currentTreeRevision(root) resolves "" there, so a test that cares about the
// revision comparison passes opts.Revision explicitly rather than depending on
// this session's own git state) plus one empty stream directory under it.
func mustCoverageStream(t *testing.T, name string) (*Stream, string) {
	t.Helper()
	root := t.TempDir()
	dir := filepath.Join(root, "docs", "streams", name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	return &Stream{Name: name, Dir: dir, Root: root}, root
}

// TestCoverage is the baseline: one Verify row with a matching, passing witness
// releases the brief with exactly one `pass` claim.
func TestCoverage(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	// The witness must be corroborable against real history (review finding F3,
	// round 2: an unreadable historical row is could-not-check, never pass), so
	// the brief's Verify row is committed first and the witness names that
	// commit — the in-progress shape: HEAD is still the tree the check ran on,
	// with only the Evidence write uncommitted on top.
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	witnessTree := mustGitInit(t, root)
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c, ok := cov["cov/01"]
	if !ok {
		t.Fatalf("no coverage computed for cov/01 (got %+v)", cov)
	}
	if !c.Released {
		t.Fatalf("want released, got held: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covPass {
		t.Fatalf("want exactly one pass claim, got %+v", c.Claims)
	}
}

// TestCoverageNoTargetRevisionIsCouldNotCheck — review finding F1, case 2: an
// unreadable/absent item revision must never default a witness to `pass`. A
// witness with a well-formed tree token, but no established target to compare
// it against, resolves `could-not-check`, not `pass`.
func TestCoverageNoTargetRevisionIsCouldNotCheck(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "abc123def456"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{}) // no Revision override; root has no git history
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("an unestablished item revision must never release the brief, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covCouldNotCheck {
		t.Fatalf("want could-not-check, got %+v", c.Claims)
	}
}

// TestCoverageMissingTreeTokenIsCouldNotCheck — review finding F1, case 1: a
// witness with NO tree token at all, against a KNOWN item revision, must never
// default to `pass` just because there was nothing to contradict it.
func TestCoverageMissingTreeTokenIsCouldNotCheck(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "")) // no @ tree token
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{Revision: "abc123def456"})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a witness with no tree token must never release against a known item revision, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covCouldNotCheck {
		t.Fatalf("want could-not-check, got %+v", c.Claims)
	}
}

// TestCoverageShortTreeTokenIsCouldNotCheck — review finding F1, case 3: a
// tree token shorter than minRevisionTokenLen must never be read as a match
// (a 1-character token matches roughly 1 in 16 real SHAs by coincidence).
func TestCoverageShortTreeTokenIsCouldNotCheck(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "a"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	// The target starts with the same single character, so the old
	// shortest-prefix comparison would have called this a match.
	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{Revision: "abc123def456"})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a 1-character tree token must never be read as a match, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covCouldNotCheck {
		t.Fatalf("want could-not-check, got %+v", c.Claims)
	}
}

// TestCoverageWrongRevisionHolds — a witness whose recorded tree SHA differs
// from the item's revision is `wrong-revision`, and the brief is held, never
// released on the strength of a witness proven only for a different commit.
func TestCoverageWrongRevisionHolds(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "aaaaaaaaaaaa"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{Revision: "bbbbbbbbbbbb"})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a witness at the wrong revision must hold the brief, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covWrongRevision {
		t.Fatalf("want wrong-revision, got %+v", c.Claims)
	}
}

// TestCoverageCouldNotCheckIsNotPass — a `could-not-run` witness resolves
// `could-not-check` and holds; it must never be read as pass.
func TestCoverageCouldNotCheckIsNotPass(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", stateCouldNotRun, "abc123def456"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("could-not-run must never release the brief, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covCouldNotCheck {
		t.Fatalf("want could-not-check, got %+v", c.Claims)
	}
}

// TestCoverageJoinRequiresIntegrationRow — Task item 2: a brief bound to the
// pattern's join node needs at least one Verify row classed `+flow`;
// individually-passing site rows alone do not release the join. No adapter
// exists yet (this brief's integration amendment), so the binding and the
// parsed pattern are constructed directly here — exactly the
// "testable without a provider" the amendment asks for.
func TestCoverageJoinRequiresIntegrationRow(t *testing.T) {
	pat := patternDoc{
		Name: "fixture-pattern",
		Join: "verify",
		NodeByID: map[string]patternNode{
			"verify": {ID: "verify", Kind: "check", Role: "verifier"},
		},
	}
	// Each fixture root is git-backed with the Verify row committed and the
	// witness naming that commit (see TestCoverage), so the only thing that can
	// hold these briefs is the join rule itself — not F1's unestablished-revision
	// handling nor F3's unreadable-history handling.
	opts := coverageOptions{
		Bindings: map[string]coverageBinding{"cov/01": {Pattern: "fixture-pattern", Node: "verify"}},
		Patterns: map[string]patternDoc{"fixture-pattern": pat},
	}

	// Site rows only (no +flow obligation) — held on integration-check.
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Class | Command | Expect |\n|---|-------|---------|--------|\n| 1 | check | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	w1 := mustGitInit(t, root)
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, w1))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, opts)
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("individually-passing site rows must not release the join, got released: %+v", c)
	}
	foundMissingIntegration := false
	for _, cl := range c.Claims {
		if cl.Claim == "integration-check" && cl.Result == covMissing {
			foundMissingIntegration = true
		}
	}
	if !foundMissingIntegration {
		t.Fatalf("want a missing integration-check claim, got %+v", c.Claims)
	}

	// Add a +flow row — the join releases.
	s2, root2 := mustCoverageStream(t, "cov")
	verify2 := "| # | Class | Command | Expect |\n|---|-------|---------|--------|\n| 1 | check +flow | `true` | exit 0 |"
	writeCoverageBrief(t, s2.Dir, "01", "cov", verify2, "")
	w2 := mustGitInit(t, root2)
	ev2 := coverageEvidenceTable(covWitnessRow("1", "true", statePass, w2))
	writeCoverageBrief(t, s2.Dir, "01", "cov", verify2, ev2)

	cov2 := evaluateCoverage(root2, []*Stream{s2}, opts)
	c2 := cov2["cov/01"]
	if !c2.Released {
		t.Fatalf("a +flow row should release the join, got held: %+v", c2)
	}
}

// TestCoverageAdviceCannotSupplyWitness — 2026-09-18 integration amendment: "a
// model assessment is never an execution witness." Prose asserting confidence
// about a row — however emphatic — does not match verifyrun's own witness shape
// (an `exit=` marker AND a `sha256:` marker, each in its own cell), so it can
// never supply a missing mandatory claim.
func TestCoverageAdviceCannotSupplyWitness(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := "| # | Note |\n|---|------|\n| 1 | HIGH CONFIDENCE: this row passes based on a code read, no execution needed |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a model's prose advice must never supply a missing execution witness, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covMissing {
		t.Fatalf("want missing, got %+v", c.Claims)
	}
}

// TestCoverageAcceptanceDigestChanged — 2026-09-18 integration amendment:
// "applicable evidence must bind the exact subject and acceptance-definition
// digest." A witness recorded against a Verify row's PRIOR Command text no
// longer describes the row after that text changes — the witness's acceptance
// definition changed out from under it, and the claim resolves `error`, never
// `pass` on the strength of a witness for a different question.
func TestCoverageAcceptanceDigestChanged(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	// The witness was recorded for `true`; the Verify row now reads something else.
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true && echo changed` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "abc123def456"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a witness whose acceptance definition changed must not release, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covError {
		t.Fatalf("want error (stale acceptance-definition digest), got %+v", c.Claims)
	}
}

// TestCoverageResultVocabularyIsClosed pins Verify row 6's contract: the
// printed `result` field is always one of the six fixed values, whatever the
// input shape (bad table, missing brief, empty Evidence).
func TestCoverageResultVocabularyIsClosed(t *testing.T) {
	closed := map[string]bool{
		covPass: true, covFail: true, covMissing: true,
		covError: true, covCouldNotCheck: true, covWrongRevision: true,
	}
	s, root := mustCoverageStream(t, "cov")
	writeCoverageBrief(t, s.Dir, "01", "cov",
		"| # | Command | Expect |\n|---|---------|--------|\n| 1 | `false` | exit 0 |",
		coverageEvidenceTable(covWitnessRow("1", "false", stateFail, "abc123def456")))
	writeCoverageBrief(t, s.Dir, "02", "cov",
		"| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |",
		"") // no evidence at all -> missing

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	for id, c := range cov {
		for _, cl := range c.Claims {
			if !closed[cl.Result] {
				t.Errorf("%s: claim %q resolved to %q, outside the closed six-value vocabulary", id, cl.Claim, cl.Result)
			}
		}
	}
}

// ---------------------------------------------------------------------------
// git-backed fixtures — review findings F2 (ancestor revision matching) and F3
// (the Expect half of the acceptance-definition digest guard) need a REAL git
// checkout, unlike mustCoverageStream's deliberately non-git temp dir.
// ---------------------------------------------------------------------------

// mustGitHeadShort returns root's current HEAD SHA, truncated to treeSHALen —
// the same truncation currentTreeRevision/treeSHA already apply, so a witness
// stamped with this value compares like-for-like.
func mustGitHeadShort(t *testing.T, root string) string {
	t.Helper()
	out, err := exec.Command("git", "-C", root, "rev-parse", "HEAD").Output()
	if err != nil {
		t.Fatalf("git rev-parse HEAD: %v", err)
	}
	sha := strings.TrimSpace(string(out))
	if len(sha) > treeSHALen {
		sha = sha[:treeSHALen]
	}
	return sha
}

// mustGitInit turns root (already populated with fixture files) into a real
// git repo with everything on disk committed, and returns the resulting HEAD.
// The commit identity is a fixed, throwaway one (runGit is gitinfo_test.go's
// shared helper — `git -C` is never used here since that helper runs the
// command with cmd.Dir set instead), never the ambient user's.
func mustGitInit(t *testing.T, root string) string {
	t.Helper()
	runGit(t, root, "init", "-q")
	runGit(t, root, "config", "user.email", "fixture@example.com")
	runGit(t, root, "config", "user.name", "fixture")
	runGit(t, root, "config", "commit.gpgsign", "false")
	runGit(t, root, "add", "-A")
	runGit(t, root, "commit", "-q", "-m", "fixture: initial")
	return mustGitHeadShort(t, root)
}

// mustGitCommitAll commits every change currently on disk in an ALREADY-git
// root and returns the new HEAD.
func mustGitCommitAll(t *testing.T, root, message string) string {
	t.Helper()
	runGit(t, root, "add", "-A")
	runGit(t, root, "-c", "commit.gpgsign=false", "commit", "-q", "-m", message)
	return mustGitHeadShort(t, root)
}

// TestCoverageAncestorWitnessReleases — review finding F2: a witness is
// committed as PART OF the Evidence write that records it, so by the time
// anyone reads that Evidence, HEAD has already moved past the tree the
// witness ran on. Treating that as a plain mismatch would refuse EVERY real
// witness forever — the review's own reproduction: 287/287 briefs held, 0
// released, on this PR's own tree. classifyRevision must still release when
// the witness tree is an ancestor of HEAD and nothing but the brief's own
// file changed since (the ordinary "run the check, then commit the Evidence"
// shape).
func TestCoverageAncestorWitnessReleases(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "") // no Evidence yet — this is the tree the check ran against
	witnessTree := mustGitInit(t, root)

	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev) // the ONLY change: the brief's own Evidence
	head := mustGitCommitAll(t, root, "record Evidence")
	if head == witnessTree {
		t.Fatalf("the Evidence commit must move HEAD past the witness tree for this test to mean anything (both %s)", head)
	}

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if !c.Released {
		t.Fatalf("a witness tree that is an ancestor of HEAD, with only the brief's own file changed since, must release — got held: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covPass {
		t.Fatalf("want pass, got %+v", c.Claims)
	}
}

// TestCoverageAncestorWitnessOtherPathChangedMismatch — the F2 fix's other
// side: when something BESIDES the brief's own file changed after the witness
// ran, the witness no longer speaks for today's code, and coverage must still
// report `wrong-revision` rather than crediting the ancestor relationship
// alone. The brief declares no `files:` line, so the witness speaks for every
// path outside the board's own bookkeeping (round-2 F2 scope rule) — a change
// to an implementation path (src/, not docs/streams/** or STATUS.md) holds it.
func TestCoverageAncestorWitnessOtherPathChangedMismatch(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	if err := os.MkdirAll(filepath.Join(root, "src"), 0o755); err != nil {
		t.Fatal(err)
	}
	other := filepath.Join(root, "src", "other.txt")
	if err := os.WriteFile(other, []byte("v1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	witnessTree := mustGitInit(t, root)

	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)
	if err := os.WriteFile(other, []byte("v2\n"), 0o644); err != nil { // real implementation change, not just Evidence
		t.Fatal(err)
	}
	mustGitCommitAll(t, root, "record Evidence and change other.txt")

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a real change to another path after the witness ran must still hold the brief, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covWrongRevision {
		t.Fatalf("want wrong-revision, got %+v", c.Claims)
	}
}

// TestCoverageExpectChangedSinceWitnessRan — review finding F3: an Expect-only
// tightening after the witness ran is invisible to the Command-text guard
// alone. classifyRevision here resolves a match (only the brief's own file
// changed, same as TestCoverageAncestorWitnessReleases), so this pins that the
// SEPARATE Expect-history guard (verifyRowAtRevision) still catches it.
func TestCoverageExpectChangedSinceWitnessRan(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	witnessTree := mustGitInit(t, root)

	verifyTightened := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0; output contains READY |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
	writeCoverageBrief(t, s.Dir, "01", "cov", verifyTightened, ev)
	mustGitCommitAll(t, root, "tighten Expect and record Evidence")

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("an Expect change since the witness ran must never release on the strength of a witness for a different question, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covError {
		t.Fatalf("want error (stale acceptance-definition digest), got %+v", c.Claims)
	}
}

// ---------------------------------------------------------------------------
// Round-2 review (head e43403dfd): F2 — the witness scope; F3 — the Expect
// guard must never be skipped into a `pass`; S3/A5 — the declared `+dirty`
// tolerance.
// ---------------------------------------------------------------------------

// mustWriteFile writes content to root/rel, creating parent directories.
func mustWriteFile(t *testing.T, root, rel, content string) {
	t.Helper()
	p := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestCoverageDirtyWitnessExpectChangedIsError — round-2 F3(a) / security S1
// (the review's PROBE-F): a witness recorded over an uncommitted tree carries
// `@ <sha>+dirty`, the ordinary verifyrun shape. The Expect-history guard must
// read the row at the witness's BASE commit (suffix stripped) and still catch
// an Expect tightened after the run — never skip itself into a `pass`.
func TestCoverageDirtyWitnessExpectChangedIsError(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	witnessTree := mustGitInit(t, root)

	verifyTightened := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0; output contains READY |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree+"+dirty"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verifyTightened, ev)
	mustGitCommitAll(t, root, "tighten Expect and record a +dirty witness")

	c := evaluateCoverage(root, []*Stream{s}, coverageOptions{})["cov/01"]
	if c.Released {
		t.Fatalf("a +dirty witness must not skip the Expect guard into a release, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covError {
		t.Fatalf("want error (stale acceptance-definition digest), got %+v", c.Claims)
	}
}

// TestCoverageBriefAbsentAtWitnessTreeIsCouldNotCheck — round-2 F3(b) / security
// S2 (PROBE-G): the brief did not exist at the witness's tree (first committed
// together with its Evidence), so the row the witness answered cannot be read.
// That is could-not-check — uncorroborated is never `pass`.
func TestCoverageBriefAbsentAtWitnessTreeIsCouldNotCheck(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	mustWriteFile(t, root, "src/impl.txt", "v1\n")
	witnessTree := mustGitInit(t, root) // the brief is NOT in this tree

	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0; output contains READY |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)
	mustGitCommitAll(t, root, "add the brief together with its Evidence")

	c := evaluateCoverage(root, []*Stream{s}, coverageOptions{})["cov/01"]
	if c.Released {
		t.Fatalf("a witness whose Verify row cannot be read at its own tree must never release, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covCouldNotCheck {
		t.Fatalf("want could-not-check, got %+v", c.Claims)
	}
}

// TestCoverageRowAbsentAtWitnessTreeIsCouldNotCheck — round-2 F3(b): the brief
// existed at the witness's tree, but the row id did not (it was added after).
func TestCoverageRowAbsentAtWitnessTreeIsCouldNotCheck(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	writeCoverageBrief(t, s.Dir, "01", "cov", "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |", "")
	witnessTree := mustGitInit(t, root)

	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |\n| 2 | `true` | exit 0 |"
	ev := coverageEvidenceTable(
		covWitnessRow("1", "true", statePass, witnessTree),
		covWitnessRow("2", "true", statePass, witnessTree),
	)
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)
	mustGitCommitAll(t, root, "add row 2 and record Evidence for both")

	c := evaluateCoverage(root, []*Stream{s}, coverageOptions{})["cov/01"]
	if c.Released {
		t.Fatalf("row 2 did not exist at the witness's tree, so the brief must not release, got released: %+v", c)
	}
	got := map[string]string{}
	for _, cl := range c.Claims {
		got[cl.Claim] = cl.Result
	}
	if got["Verify row #1: true"] != covPass || got["Verify row #2: true"] != covCouldNotCheck {
		t.Fatalf("want row 1 pass, row 2 could-not-check; got %+v", c.Claims)
	}
}

// TestCoverageSiblingEvidenceAndStatusRegenStillRelease — round-2 F2 (PROBE-D
// and PROBE-E): the model-lane flip runs at the main tip, and between the
// witness tree and that tip a verify batch lands Evidence for SEVERAL briefs in
// one commit and statusgen regenerates STATUS.md after every push. That board
// bookkeeping is not something the witness speaks for; it must not turn a
// witness into `wrong-revision`.
func TestCoverageSiblingEvidenceAndStatusRegenStillRelease(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	writeCoverageBrief(t, s.Dir, "02", "cov", verify, "")
	mustWriteFile(t, root, "STATUS.md", "board v1\n")
	witnessTree := mustGitInit(t, root)

	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)
	writeCoverageBrief(t, s.Dir, "02", "cov", verify, ev) // sibling brief's Evidence, same batch commit
	mustWriteFile(t, root, "docs/streams/verify-outcomes.jsonl", "{}\n")
	mustGitCommitAll(t, root, "verify batch: Evidence for 01 and 02")
	mustWriteFile(t, root, "STATUS.md", "board v2\n")
	mustGitCommitAll(t, root, "chore(status): regenerate")

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	for _, id := range []string{"cov/01", "cov/02"} {
		c := cov[id]
		if !c.Released || len(c.Claims) != 1 || c.Claims[0].Result != covPass {
			t.Fatalf("%s: sibling Evidence plus a STATUS.md regen must not invalidate the witness, got %+v", id, c)
		}
	}
}

// TestCoverageDeclaredFilesScopeTheWitness — round-2 F2: when the brief
// declares `files:` AND a complete dependency manifest licenses narrowing
// (WI-2), those paths are what the witness speaks for. A change to an
// undeclared implementation path after the witness ran releases; a change to a
// declared path (including one under a declared directory) holds. Without the
// manifest the undeclared change holds too (TestCoverageReuseDoesNotRetargetPass).
func TestCoverageDeclaredFilesScopeTheWitness(t *testing.T) {
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	// No prose annotation: since round 5 a word outside the spans, such as
	// `(planned)`, is an entry that names nothing and widens to conservative.
	files := "`src/impl.go`, `src/pkg/`"
	cases := []struct {
		name    string
		changed string
		want    string
	}{
		{"undeclared path changed releases", "src/unrelated.go", covPass},
		{"declared file changed holds", "src/impl.go", covWrongRevision},
		{"path under a declared directory holds", "src/pkg/inner.go", covWrongRevision},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			s, root := mustCoverageStream(t, "cov")
			writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", files, verify, "")
			// Every declared entry names a real path at the witness tree — a
			// declaration that resolves to nothing falls back to the
			// conservative scope (round-3 F6), which is not what this test pins.
			mustWriteFile(t, root, "src/impl.go", "v1\n")
			mustWriteFile(t, root, "src/pkg/inner.go", "v1\n")
			mustWriteFile(t, root, tc.changed, "v1\n")
			witnessTree := mustGitInit(t, root)

			ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
			writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", files, verify, ev)
			mustWriteFile(t, root, tc.changed, "v2\n")
			mustGitCommitAll(t, root, "record Evidence; change "+tc.changed)

			c := evaluateCoverage(root, []*Stream{s}, withManifest(true))["cov/01"]
			if len(c.Claims) != 1 || c.Claims[0].Result != tc.want {
				t.Fatalf("changed %s: want %s, got %+v", tc.changed, tc.want, c.Claims)
			}
		})
	}
}

// TestCoverageDirtyWitnessToleranceIsDeclared pins the round-2 S3/A5 decision
// (coverage.go header, "THE +dirty TOLERANCE"): a `+dirty` witness is compared
// by its base commit, on both the exact and the ancestor path, and every other
// guard still binds. This is a DELIBERATE, documented tolerance — if it is ever
// narrowed, this test is the one to change, in the same commit as the spec.
func TestCoverageDirtyWitnessToleranceIsDeclared(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	witnessTree := mustGitInit(t, root)

	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree+"+dirty"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)
	mustGitCommitAll(t, root, "record a +dirty witness")

	c := evaluateCoverage(root, []*Stream{s}, coverageOptions{})["cov/01"]
	if !c.Released || len(c.Claims) != 1 || c.Claims[0].Result != covPass {
		t.Fatalf("the declared +dirty tolerance: want pass at the base commit, got %+v", c)
	}
}

// ---------------------------------------------------------------------------
// Round-3 review (head 5980c2acb): F2 — the declared-`files:` branch must not
// hold on the board bookkeeping verify and regen necessarily write; F6 (security
// pr1682-S5) — the witness scope must never RELEASE after a path it speaks for
// changed (renames, declarations that resolve to nothing, a `files:` line
// narrowed after the run); A7 — the brief-own-file exemption is pinned.
// ---------------------------------------------------------------------------

// coverageScopeScenario runs the one shape every round-3 probe shares: write the
// brief with filesAtW (plus whatever setup writes), commit that as the witness
// tree W, then in ONE later commit record a passing witness at W, rewrite the
// brief's `files:` line to filesAfter, and apply change. It returns the single
// Verify-row claim coverage resolves at the new HEAD. It supplies a complete,
// otherwise empty dependency manifest: since the work-input amendment (WI-2)
// only a complete manifest licenses narrowing to `files:` at all, and these
// probes pin how that narrowing behaves.
func coverageScopeScenario(t *testing.T, filesAtW, filesAfter string, setup, change func(t *testing.T, root string)) Claim {
	t.Helper()
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", filesAtW, verify, "")
	if setup != nil {
		setup(t, root)
	}
	witnessTree := mustGitInit(t, root)

	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
	writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", filesAfter, verify, ev)
	if change != nil {
		change(t, root)
	}
	mustGitCommitAll(t, root, "record Evidence and apply the change")

	c := evaluateCoverage(root, []*Stream{s}, withManifest(true))["cov/01"]
	if len(c.Claims) != 1 {
		t.Fatalf("want exactly one claim, got %+v", c.Claims)
	}
	return c.Claims[0]
}

// writes returns a setup/change func that writes each rel=content pair.
func writes(kv ...string) func(t *testing.T, root string) {
	return func(t *testing.T, root string) {
		t.Helper()
		for i := 0; i+1 < len(kv); i += 2 {
			mustWriteFile(t, root, kv[i], kv[i+1])
		}
	}
}

// TestCoverageDeclaredScopeExemptsVerifyBookkeeping — round-3 F2 (probes R1,
// R2): a brief whose `files:` names its own stream README, STATUS.md, or the
// whole docs/streams/ tree must not go `wrong-revision` forever when its own
// verified flip, a sibling's Evidence, a verify-outcomes append or a STATUS.md
// regen lands — those are the surfaces verify and regen necessarily write. Any
// OTHER declared docs/streams/ artifact still holds.
func TestCoverageDeclaredScopeExemptsVerifyBookkeeping(t *testing.T) {
	readme := func(state string) string {
		return "| # | Brief | Status |\n|---|---|---|\n| 01 | fixture | " + state + " |\n"
	}
	cases := []struct {
		name   string
		files  string
		setup  func(t *testing.T, root string)
		change func(t *testing.T, root string)
		want   string
	}{
		{
			"R1 declared stream README, own row flips to verified",
			"`src/impl.go`, `docs/streams/cov/README.md`",
			writes("src/impl.go", "v1\n", "docs/streams/cov/README.md", readme("implemented")),
			writes("docs/streams/cov/README.md", readme("verified")),
			covPass,
		},
		{
			"R2 declared STATUS.md, regen lands",
			"`src/impl.go`, `STATUS.md`",
			writes("src/impl.go", "v1\n", "STATUS.md", "board v1\n"),
			writes("STATUS.md", "board v2\n"),
			covPass,
		},
		{
			"whole docs/streams declared, sibling Evidence + verify-outcomes + README",
			"`docs/streams/`, `src/impl.go`",
			writes("src/impl.go", "v1\n", "docs/streams/cov/README.md", readme("implemented"), "docs/streams/other/brief-02.md", "sibling v1\n", "docs/streams/verify-outcomes.jsonl", "{}\n"),
			writes("docs/streams/cov/README.md", readme("verified"), "docs/streams/other/brief-02.md", "sibling v2\n", "docs/streams/verify-outcomes.jsonl", "{}\n{}\n"),
			covPass,
		},
		{
			"declared non-README docs/streams artifact changed still holds",
			"`src/impl.go`, `docs/streams/cov/ruleset-audit.md`",
			writes("src/impl.go", "v1\n", "docs/streams/cov/ruleset-audit.md", "audit v1\n"),
			writes("docs/streams/cov/ruleset-audit.md", "audit v2\n"),
			covWrongRevision,
		},
		{
			"whole docs/streams declared, a non-bookkeeping artifact under it changed holds",
			"`docs/streams/`, `src/impl.go`",
			writes("src/impl.go", "v1\n", "docs/streams/cov/ruleset-audit.md", "audit v1\n"),
			writes("docs/streams/cov/ruleset-audit.md", "audit v2\n"),
			covWrongRevision,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := coverageScopeScenario(t, tc.files, tc.files, tc.setup, tc.change)
			if got.Result != tc.want {
				t.Fatalf("want %s, got %+v", tc.want, got)
			}
		})
	}
}

// TestCoverageWitnessScopeNeverFailsOpen — round-3 F6 / security pr1682-S5: every
// shape the reviewers probed at 5980c2acb released a witness (Result pass) after
// a path it speaks for changed. Each must now resolve `wrong-revision`: renames
// are listed on both sides (`--no-renames`), a declaration with an entry that
// resolves to no path (brace form, `.`, prose, a bare sibling name, a `**`
// nesting glob) falls back to the conservative no-declaration scope instead of
// speaking for nothing, and the scope is read from the brief at the witness's
// base commit as well as now, so narrowing `files:` afterwards is visible.
func TestCoverageWitnessScopeNeverFailsOpen(t *testing.T) {
	gitMv := func(from, to string) func(t *testing.T, root string) {
		return func(t *testing.T, root string) {
			t.Helper()
			if err := os.MkdirAll(filepath.Dir(filepath.Join(root, filepath.FromSlash(to))), 0o755); err != nil {
				t.Fatal(err)
			}
			runGit(t, root, "mv", from, to)
		}
	}
	both := func(fs ...func(t *testing.T, root string)) func(t *testing.T, root string) {
		return func(t *testing.T, root string) {
			for _, f := range fs {
				f(t, root)
			}
		}
	}
	impl := "package impl\n\nfunc A() int { return 1 }\n\nfunc B() int { return 2 }\n\nfunc C() int { return 3 }\n"
	cases := []struct {
		name               string
		filesAtW, filesNow string
		setup, change      func(t *testing.T, root string)
	}{
		{"S5a declared file renamed", "`src/impl.go`", "`src/impl.go`",
			writes("src/impl.go", impl), gitMv("src/impl.go", "src/impl2.go")},
		{"S5a' declared file renamed and edited", "`src/impl.go`", "`src/impl.go`",
			writes("src/impl.go", impl), both(gitMv("src/impl.go", "src/impl2.go"), writes("src/impl2.go", impl+"\nfunc D() int { return 4 }\n"))},
		{"S5b no files:, moved into docs/streams", "", "",
			writes("src/impl.go", impl), gitMv("src/impl.go", "docs/streams/x/impl.go")},
		{"S5c brace-form declaration", "`src/{impl.go,b.go}`", "`src/{impl.go,b.go}`",
			writes("src/impl.go", "v1\n", "src/b.go", "v1\n"), writes("src/impl.go", "v2\n")},
		{"S5d files: .", "`.`", "`.`",
			writes("src/impl.go", "v1\n"), writes("src/impl.go", "v2\n")},
		{"S5e files: n/a", "n/a", "n/a",
			writes("src/impl.go", "v1\n"), writes("src/impl.go", "v2\n")},
		{"S5f files: narrowed after the witness ran", "`src/impl.go`, `src/b.go`", "`src/impl.go`",
			writes("src/impl.go", "v1\n", "src/b.go", "v1\n"), writes("src/b.go", "v2\n")},
		{"S5f' files: added after a no-declaration witness", "", "`unrelated/x.go`",
			writes("src/impl.go", "v1\n", "unrelated/x.go", "v1\n"), writes("src/impl.go", "v2\n")},
		{"X1 bare sibling shorthand", "`src/impl.go`, `b.go`", "`src/impl.go`, `b.go`",
			writes("src/impl.go", "v1\n", "src/b.go", "v1\n"), writes("src/b.go", "v2\n")},
		{"X2 ** nesting glob", "`src/**`", "`src/**`",
			writes("src/a/deep.go", "v1\n"), writes("src/a/deep.go", "v2\n")},
		{"X3 mid-pattern ** that path.Match reads as one segment", "`src/**/*.go`", "`src/**/*.go`",
			writes("src/a/x.go", "v1\n", "src/a/b/y.go", "v1\n"), writes("src/a/b/y.go", "v2\n")},
		// Round-4 re-review (head 981623aeb, review 5330931191): F6 / security S6
		// — a `files:` token with no '/' and no '.' was dropped by the
		// path-shape filter before it ever reached declaredEntryResolves, so a
		// REAL dotless declaration (a top-level `Makefile`, a bare directory
		// name) was silently left outside the scope (P1-P3), and a dotless
		// token naming nothing never forced the conservative fallback the way
		// its dotted counterpart already did (P6).
		{"P1 backticked dotless declared file (Makefile)", "`src/impl.go`, `Makefile`", "`src/impl.go`, `Makefile`",
			writes("src/impl.go", "v1\n", "Makefile", "v1\n"), writes("Makefile", "v2\n")},
		{"P2 backticked dotless declared directory", "`src/impl.go`, `tools`", "`src/impl.go`, `tools`",
			writes("src/impl.go", "v1\n", "tools/x.go", "v1\n"), writes("tools/x.go", "v2\n")},
		{"P3 unbackticked inline dotless declared file", "src/impl.go, Makefile", "src/impl.go, Makefile",
			writes("src/impl.go", "v1\n", "Makefile", "v1\n"), writes("Makefile", "v2\n")},
		{"P6 backticked dotless entry resolving to nothing falls back conservative", "`src/impl.go`, `nosuchthing`", "`src/impl.go`, `nosuchthing`",
			writes("src/impl.go", "v1\n", "lib/other.go", "v1\n"), writes("lib/other.go", "v2\n")},
		// Round-5 re-review (head 17e215ae4): F6 / security S10 — the inline
		// parser kept ONLY backtick spans once any span was present, so a plain
		// entry beside a backticked one (I1), prose around it (I3), an
		// unresolvable plain entry (I4) and a value wrapped onto a continuation
		// line (W1, W2) all dropped out of the scope and released.
		{"I1 plain entry beside a backticked one", "`src/impl.go`, lib/other.go", "`src/impl.go`, lib/other.go",
			writes("src/impl.go", "v1\n", "lib/other.go", "v1\n"), writes("lib/other.go", "v2\n")},
		{"I3 prose around a backticked entry", "`src/impl.go` and lib/other.go (new)", "`src/impl.go` and lib/other.go (new)",
			writes("src/impl.go", "v1\n", "lib/other.go", "v1\n"), writes("lib/other.go", "v2\n")},
		{"I4 plain entry naming nothing", "`src/impl.go`, nosuch.go", "`src/impl.go`, nosuch.go",
			writes("src/impl.go", "v1\n", "lib/unrelated.go", "v1\n"), writes("lib/unrelated.go", "v2\n")},
		{"W1 span wrapped onto a continuation line", "`src/impl.go`, `lib/{a,b,\n  c}.go`", "`src/impl.go`, `lib/{a,b,\n  c}.go`",
			writes("src/impl.go", "v1\n", "lib/c.go", "v1\n"), writes("lib/c.go", "v2\n")},
		{"W2 entry on a continuation line", "`src/impl.go`,\n  `lib/c.go`", "`src/impl.go`,\n  `lib/c.go`",
			writes("src/impl.go", "v1\n", "lib/c.go", "v1\n"), writes("lib/c.go", "v2\n")},
		// Security S6: a declaration whose every entry is exempt speaks for
		// nothing; it must fall back to the conservative scope.
		{"S6 every declared entry exempt", "`STATUS.md`", "`STATUS.md`",
			writes("src/impl.go", "v1\n", "STATUS.md", "board v1\n"), writes("src/impl.go", "v2\n")},
		// A8 / security S11: pins each half of the dotless-entry fix separately.
		{"P4 plain bullet beside a backticked bullet", "\n- `src/impl.go`\n- lib/other.go", "\n- `src/impl.go`\n- lib/other.go",
			writes("src/impl.go", "v1\n", "lib/other.go", "v1\n"), writes("lib/other.go", "v2\n")},
		{"P7 dotless entry declared only at the witness", "`src/impl.go`, `tools`", "`src/impl.go`",
			writes("src/impl.go", "v1\n", "tools/x.go", "v1\n"), writes("tools/x.go", "v2\n")},
		{"P8 dotless entry declared only now", "`src/impl.go`", "`src/impl.go`, `tools`",
			writes("src/impl.go", "v1\n", "tools/x.go", "v1\n"), writes("tools/x.go", "v2\n")},
		// The same defect class in the bulleted form: a bullet that carries a
		// span dropped every word outside it.
		{"B1 plain entry beside a span in one bullet", "\n- `src/impl.go` and lib/other.go", "\n- `src/impl.go` and lib/other.go",
			writes("src/impl.go", "v1\n", "lib/other.go", "v1\n"), writes("lib/other.go", "v2\n")},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := coverageScopeScenario(t, tc.filesAtW, tc.filesNow, tc.setup, tc.change)
			if got.Result != covWrongRevision {
				t.Fatalf("a change to a path the witness speaks for must hold as wrong-revision, got %+v", got)
			}
		})
	}
}

// TestCoverageResolvableDeclarationsStillScope — the other side of F6: the
// conservative fallback is for declarations that name NOTHING real. A
// declaration whose every entry resolves keeps its narrow scope (a change
// outside it releases), including a trailing `/**` directory glob and a
// one-segment glob path.Match can express.
func TestCoverageResolvableDeclarationsStillScope(t *testing.T) {
	cases := []struct {
		name  string
		files string
		setup func(t *testing.T, root string)
	}{
		{"trailing /** reads as the directory", "`src/**`", writes("src/a/deep.go", "v1\n", "lib/other.go", "v1\n")},
		{"one-segment glob", "`src/*.go`", writes("src/impl.go", "v1\n", "lib/other.go", "v1\n")},
		{"plain declared file", "`src/impl.go`", writes("src/impl.go", "v1\n", "lib/other.go", "v1\n")},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := coverageScopeScenario(t, tc.files, tc.files, tc.setup, writes("lib/other.go", "v2\n"))
			if got.Result != covPass {
				t.Fatalf("a change outside a fully-resolving declaration must release, got %+v", got)
			}
		})
	}
	// ...and the same one-segment glob still HOLDS on a change it covers.
	got := coverageScopeScenario(t, "`src/*.go`", "`src/*.go`", writes("src/impl.go", "v1\n"), writes("src/impl.go", "v2\n"))
	if got.Result != covWrongRevision {
		t.Fatalf("a change the glob covers must hold, got %+v", got)
	}
}

// TestCoverageBriefOwnFileNeverInvalidates — round-3 A7: the brief's own file is
// exempt from the witness scope (its Verify rows are bound by the Command and
// Expect guards instead). The fixture stream lives OUTSIDE docs/streams/ so no
// bookkeeping exemption also covers the brief's path — this test is the only
// thing standing between that exemption and a mutation that removes it.
func TestCoverageBriefOwnFileNeverInvalidates(t *testing.T) {
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	for _, files := range []string{"", "`plans/cov/brief-01.md`, `src/impl.go`"} {
		t.Run("files="+files, func(t *testing.T) {
			root := t.TempDir()
			dir := filepath.Join(root, "plans", "cov")
			if err := os.MkdirAll(dir, 0o755); err != nil {
				t.Fatal(err)
			}
			s := &Stream{Name: "cov", Dir: dir, Root: root}
			mustWriteFile(t, root, "src/impl.go", "v1\n")
			writeCoverageBriefWithFiles(t, dir, "01", "cov", files, verify, "")
			witnessTree := mustGitInit(t, root)
			ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
			writeCoverageBriefWithFiles(t, dir, "01", "cov", files, verify, ev)
			mustGitCommitAll(t, root, "record Evidence (the brief's own file is the only change)")
			c := evaluateCoverage(root, []*Stream{s}, coverageOptions{})["cov/01"]
			if !c.Released || len(c.Claims) != 1 || c.Claims[0].Result != covPass {
				t.Fatalf("a change to only the brief's own file must release, got %+v", c)
			}
		})
	}
}

// -----------------------------------------------------------------------------
// Round-4 re-review (head 981623aeb, review 5330940083): S8 — a witness tree
// token must be SHA-shaped before it is ever handed to git as a revision
// expression; S9 — the two fail-closed guards a bound `observe` claim and a
// zero-claim brief depend on now each have a test that fails when the guard is
// removed.
// -----------------------------------------------------------------------------

// TestCoverageWitnessTokenMustBeHexShaped — security pr1682-S8:
// classifyRevision compared a witness's recorded tree token to the item's
// revision by handing it to git as a raw revision expression, with no check
// that it was a commit SHA. A hand-edited Evidence row can carry a SYMBOLIC
// expression instead — `HEAD^{commit}` here, at least `minRevisionTokenLen`
// characters and not itself hex — which git resolves to whatever is currently
// checked out. That makes it its own ancestor with an empty diff forever, so
// the claim reads `pass` even after the declared file it speaks for changes:
// unlike a forged-but-real hex SHA, which goes `wrong-revision` on the very
// next in-scope change, a symbolic token never does. `verifyrun` itself only
// ever writes a hex SHA (treeSHALen), so only a hand-edited row can carry this
// shape.
func TestCoverageWitnessTokenMustBeHexShaped(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", "`src/impl.go`", verify, "")
	mustWriteFile(t, root, "src/impl.go", "v1\n")
	mustGitInit(t, root)

	// Hand-edited Evidence: a symbolic tree token — not a hex SHA — that
	// nonetheless resolves to the checked-out HEAD via git.
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "HEAD^{commit}"))
	writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", "`src/impl.go`", verify, ev)
	mustWriteFile(t, root, "src/impl.go", "v2\n")
	mustGitCommitAll(t, root, "record Evidence with a symbolic witness token; change the declared file")

	c := evaluateCoverage(root, []*Stream{s}, coverageOptions{})["cov/01"]
	if len(c.Claims) != 1 {
		t.Fatalf("want exactly one claim, got %+v", c.Claims)
	}
	if got := c.Claims[0].Result; got == covPass {
		t.Fatalf("a non-hex witness token must never resolve pass after the declared file it speaks for changed, got %+v", c.Claims[0])
	}
}

// TestCoverageBoundObserveClaimHolds — security pr1682-S9(1): a
// workflow-pattern-v1 node's mandatory `observe` evidence entry has no reader
// wired yet (resolvePatternEvidenceClaim always resolves it could-not-check,
// with or without a `source`), so a brief bound to such a node must be HELD,
// never vacuously released. No committed test exercised this before — the
// reviewer's M-b mutation (observe resolves `pass`) survived the full suite.
func TestCoverageBoundObserveClaimHolds(t *testing.T) {
	pat := patternDoc{
		Name: "fixture-observe-pattern",
		NodeByID: map[string]patternNode{
			"deploy": {ID: "deploy", Kind: "effect", Role: "deployer", Evidence: []patternEvidence{
				{Kind: "observe", Claim: "error-rate-window", Mandatory: true, Source: "prometheus:error-rate"},
			}},
		},
	}
	opts := coverageOptions{
		Bindings: map[string]coverageBinding{"cov/01": {Pattern: "fixture-observe-pattern", Node: "deploy"}},
		Patterns: map[string]patternDoc{"fixture-observe-pattern": pat},
	}
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	w := mustGitInit(t, root)
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, w))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, opts)
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a bound mandatory observe claim has no reader wired yet and must hold, got released: %+v", c)
	}
	found := false
	for _, cl := range c.Claims {
		if cl.Claim == "error-rate-window" && cl.Result == covCouldNotCheck {
			found = true
		}
	}
	if !found {
		t.Fatalf("want a could-not-check claim for the observe evidence entry, got %+v", c.Claims)
	}
}

// TestCoverageZeroClaimsBriefIsHeld — security pr1682-S9(2): a brief with no
// Verify rows and no pattern binding has nothing coverage can corroborate, so
// it must be HELD, never vacuously released. No committed test constructed a
// genuinely zero-claim brief before — the reviewer's M-d mutation (this guard
// removed) survived the full suite.
func TestCoverageZeroClaimsBriefIsHeld(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	writeCoverageBrief(t, s.Dir, "01", "cov", "", "")
	mustGitInit(t, root)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a brief with no Verify rows and no pattern binding must be held, not vacuously released, got %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covMissing {
		t.Fatalf("want exactly one missing claim, got %+v", c.Claims)
	}
}

// -----------------------------------------------------------------------------
// Work-input amendment (2026-09-30, WI-2): Verify rows 13 and 14. Declared
// `files:` alone never licenses reuse ("file non-overlap is not proof"); a
// reused witness keeps its own revision; a changed policy/build/environment
// dependency holds the claim that depends on it.
// -----------------------------------------------------------------------------

// withManifest returns options carrying a dependency manifest for cov/01.
func withManifest(complete bool, deps ...workInputDep) coverageOptions {
	return coverageOptions{Dependencies: map[string]dependencyManifest{
		"cov/01": {Complete: complete, Deps: deps},
	}}
}

// soleClaim evaluates cov/01 and returns its one Verify-row claim.
func soleClaim(t *testing.T, root string, s *Stream, opts coverageOptions) Claim {
	t.Helper()
	c := evaluateCoverage(root, []*Stream{s}, opts)["cov/01"]
	if len(c.Claims) != 1 {
		t.Fatalf("want exactly one claim, got %+v", c.Claims)
	}
	return c.Claims[0]
}

// TestCoverageReuseDoesNotRetargetPass — Verify row 14, one connected flow on
// one repo: a witness passes at A; a bookkeeping-only commit reuses that
// unchanged analysis (the receipt keeps revision A, the reason states the
// derivation); an edit to a file outside the brief's `files:` — with no
// dependency manifest to prove it irrelevant — holds the claim instead of
// letting the old PASS release the new subject.
func TestCoverageReuseDoesNotRetargetPass(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	mustWriteFile(t, root, "src/impl.go", "v1\n")
	mustWriteFile(t, root, "lib/helper.go", "v1\n")
	writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", "`src/impl.go`", verify, "")
	a := mustGitInit(t, root)
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, a))
	writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", "`src/impl.go`", verify, ev)
	mustGitCommitAll(t, root, "record Evidence")

	// Unchanged analysis: only board bookkeeping moved.
	mustWriteFile(t, root, "STATUS.md", "board v2\n")
	mustWriteFile(t, root, "docs/streams/other/brief-02.md", "sibling Evidence\n")
	b := mustGitCommitAll(t, root, "verify batch + regen")
	got := soleClaim(t, root, s, coverageOptions{})
	if got.Result != covPass || got.Revision != a {
		t.Fatalf("bookkeeping-only move: want pass with the receipt kept at %s, got %+v", a, got)
	}
	if !strings.Contains(got.Reason, "reused") || !strings.Contains(got.Reason, b) {
		t.Fatalf("a reused witness must say so and name the subject it is reused at (%s), got %q", b, got.Reason)
	}

	// New subject: a source edit outside `files:`, no manifest.
	mustWriteFile(t, root, "lib/helper.go", "v2\n")
	mustGitCommitAll(t, root, "edit a helper the declared file may call")
	got = soleClaim(t, root, s, coverageOptions{})
	if got.Result != covWrongRevision || got.Revision != a {
		t.Fatalf("an old-head PASS must not release the new subject: want wrong-revision at %s, got %+v", a, got)
	}
	if !strings.Contains(got.Reason, "lib/helper.go") {
		t.Fatalf("the reason must name the invalidating path, got %q", got.Reason)
	}
}

// TestCoveragePolicyDependencyChanged — Verify row 13 (the WI-2 example
// fixture): a design at A depends on a writer's authorization policy; a later
// change alters that policy while the file the brief declares is untouched.
// The claim that depends on the policy holds as wrong-revision, naming the
// policy, and its receipt keeps revision A. A sibling claim that does not
// depend on the policy is still reused.
func TestCoveragePolicyDependencyChanged(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |\n| 2 | `true 2` | exit 0 |"
	mustWriteFile(t, root, "src/impl.go", "v1\n")
	mustWriteFile(t, root, "policy/writer-auth.yaml", "writers: [a]\n")
	writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", "`src/impl.go`", verify, "")
	a := mustGitInit(t, root)
	ev := coverageEvidenceTable(
		covWitnessRow("1", "true", statePass, a),
		covWitnessRow("2", "true 2", statePass, a),
	)
	writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", "`src/impl.go`", verify, ev)
	mustGitCommitAll(t, root, "record Evidence")
	opts := withManifest(true,
		workInputDep{Kind: depSource, Path: "src/impl.go"},
		workInputDep{Kind: depPolicy, Path: "policy/writer-auth.yaml", Rows: []string{"1"}},
	)
	claims := func() map[string]Claim {
		out := map[string]Claim{}
		for _, c := range evaluateCoverage(root, []*Stream{s}, opts)["cov/01"].Claims {
			out[c.Claim] = c
		}
		return out
	}
	if got := claims(); got["Verify row #1: true"].Result != covPass || got["Verify row #2: true 2"].Result != covPass {
		t.Fatalf("before the policy edit both claims must be reused, got %+v", got)
	}

	mustWriteFile(t, root, "policy/writer-auth.yaml", "writers: [a, b]\n")
	mustGitCommitAll(t, root, "widen the writer policy")
	got := claims()
	c1, c2 := got["Verify row #1: true"], got["Verify row #2: true 2"]
	if c1.Result != covWrongRevision || c1.Revision != a {
		t.Fatalf("row 1 depends on the policy: want wrong-revision with the receipt kept at %s, got %+v", a, c1)
	}
	if !strings.Contains(c1.Reason, "policy dependency policy/writer-auth.yaml") {
		t.Fatalf("the reason must name the invalidating policy, got %q", c1.Reason)
	}
	if c2.Result != covPass || c2.Revision != a {
		t.Fatalf("row 2 does not depend on the policy: want a reused pass at %s, got %+v", a, c2)
	}
}

// TestCoverageEnvDependency — an environment dependency is compared by its
// recorded and current fingerprints; a missing value is could-not-check.
func TestCoverageEnvDependency(t *testing.T) {
	cases := []struct {
		name, recorded, current, want string
	}{
		{"unchanged", "go1.24", "go1.24", covPass},
		{"changed", "go1.24", "go1.25", covWrongRevision},
		{"current unknown", "go1.24", "", covCouldNotCheck},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			s, root := mustCoverageStream(t, "cov")
			verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
			mustWriteFile(t, root, "src/impl.go", "v1\n")
			writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", "`src/impl.go`", verify, "")
			a := mustGitInit(t, root)
			ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, a))
			writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", "`src/impl.go`", verify, ev)
			mustGitCommitAll(t, root, "record Evidence")
			opts := withManifest(true, workInputDep{Kind: depEnvironment, Name: "toolchain", Recorded: tc.recorded, Current: tc.current})
			if got := soleClaim(t, root, s, opts); got.Result != tc.want {
				t.Fatalf("want %s, got %+v", tc.want, got)
			}
		})
	}
}

// TestCoverageManifestScopesReuse — selective reuse needs an explicit
// applicability derivation (WI-2). A helper outside `files:` changes: with no
// manifest or an incomplete one the claim holds; a complete manifest that does
// not list the helper licenses reuse and says so; one that lists the helper
// as a source dependency of the row holds.
func TestCoverageManifestScopesReuse(t *testing.T) {
	cases := []struct {
		name string
		opts coverageOptions
		want string
	}{
		{"no manifest", coverageOptions{}, covWrongRevision},
		{"incomplete manifest", withManifest(false, workInputDep{Kind: depSource, Path: "src/impl.go"}), covWrongRevision},
		{"complete manifest without the helper", withManifest(true, workInputDep{Kind: depSource, Path: "src/impl.go"}), covPass},
		{"complete manifest naming the helper", withManifest(true, workInputDep{Kind: depSource, Path: "lib/helper.go", Rows: []string{"1"}}), covWrongRevision},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			s, root := mustCoverageStream(t, "cov")
			verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
			mustWriteFile(t, root, "src/impl.go", "v1\n")
			mustWriteFile(t, root, "lib/helper.go", "v1\n")
			writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", "`src/impl.go`", verify, "")
			a := mustGitInit(t, root)
			ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, a))
			writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", "`src/impl.go`", verify, ev)
			mustWriteFile(t, root, "lib/helper.go", "v2\n")
			mustGitCommitAll(t, root, "record Evidence; edit the helper")
			got := soleClaim(t, root, s, tc.opts)
			if got.Result != tc.want || got.Revision != a {
				t.Fatalf("want %s at %s, got %+v", tc.want, a, got)
			}
			if tc.want == covPass && !strings.Contains(got.Reason, "complete dependency manifest") {
				t.Fatalf("a selective reuse must state its applicability derivation, got %q", got.Reason)
			}
		})
	}
}

// TestDeclaredEntriesKeepAll is the defect-class guard for round-5 F6 /
// security S10: whatever form a `files:` value takes, every backtick span and
// every word outside the spans reaches the witness scope as an entry, and an
// unclosed backtick makes the whole declaration untrusted (found=false).
func TestDeclaredEntriesKeepAll(t *testing.T) {
	cases := []struct {
		name, context string
		want          []string // nil = found must be false
	}{
		{"inline plain beside span", "files: `a/x.go`, b/y.go", []string{"a/x.go", "b/y.go"}},
		{"inline prose", "files: `a/x.go` and b/y.go (new)", []string{"a/x.go", "and", "b/y.go", "(new)"}},
		{"inline wrapped", "files: `a/x.go`,\n  `b/y.go`", []string{"a/x.go", "b/y.go"}},
		{"inline span wrapped mid-entry", "files: `a/x.go`, `lib/{a,b,\n  c}.go`", []string{"a/x.go", "lib/{a,b, c}.go"}},
		{"inline unclosed span", "files: `a/x.go`, `b/y.go", nil},
		{"bullet prose beside span", "files:\n- `a/x.go` and b/y.go", []string{"a/x.go", "and", "b/y.go"}},
		{"bullet plain beside bullet span", "files:\n- `a/x.go`\n- b/y.go", []string{"a/x.go", "b/y.go"}},
		{"bullet unclosed span", "files:\n- `a/x.go\n- b/y.go", nil},
		{"markdown link", "files: [a/x.go](a/x.go)", []string{"a/x.go"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, found := extractContextDeclaredEntriesRaw("## Context\n" + tc.context + "\n\n## Task\nx\n")
			if tc.want == nil {
				if found {
					t.Fatalf("an unclosed backtick must leave no trusted declaration, got %q", got)
				}
				return
			}
			if !found || strings.Join(got, "|") != strings.Join(tc.want, "|") {
				t.Fatalf("want %q, got %q (found=%v)", tc.want, got, found)
			}
		})
	}
}
