package main

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

// coverage_test.go — the evidence coverage rule (graph-execution/03). Top-level
// functions are named TestCoverage* so Verify row 1's `-run TestCoverage`
// selector counts them all.

// covWitnessRow renders one Evidence witness row exactly as verifyrun.go's own
// witness.row() would — generated by the SAME code coverage.go reads, never a
// hand-typed guess at the table format.
func covWitnessRow(id, command, state, tree string) string {
	exit := 0
	if state == stateFail {
		exit = 1
	}
	w := witness{
		ID: id, Command: command, State: state, Exit: exit,
		OutHash: "abc123def456", Date: "2026-09-25", Runner: "fixture-verifier", Tree: tree,
	}
	return w.row()
}

// coverageEvidenceTable wraps one or more witness/advice rows in the witness
// table header.
func coverageEvidenceTable(rows ...string) string {
	out := witnessHeader
	for _, r := range rows {
		out += "\n" + r
	}
	return out
}

// writeCoverageBrief writes a minimal, valid brief-v1 file (the same required-key
// shape testdata/autoflip's fixtures already use) with the given Verify/Evidence
// bodies, under dir/brief-<num>.md.
func writeCoverageBrief(t *testing.T, dir, num, streamName, verifyBody, evidenceBody string) {
	t.Helper()
	content := fmt.Sprintf(`---
brief: %s/%s
title: coverage fixture
wave: 0
depends: []
unblocks: []
effort: S
gate: model
risk: {regulatory: no, customer: no, irreversible: no, sensitive-data: no}
issues: []
schema: brief-v1
authored: 2026-09-25 by graph-execution/03 fixture
sources: ["fixture: graph-execution/03 coverage_test.go"]
---

# Brief %s — coverage fixture

## Verify
%s

## Evidence
<!-- contract comment -->

%s

## Review
Gate: model.
`, streamName, num, num, verifyBody, evidenceBody)
	if err := os.WriteFile(filepath.Join(dir, "brief-"+num+".md"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// mustCoverageStream returns a fresh temp root (deliberately NOT a git repo —
// currentTreeRevision(root) resolves "" there, so a test that cares about the
// revision comparison passes opts.Revision explicitly rather than depending on
// this session's own git state) plus one empty stream directory under it.
func mustCoverageStream(t *testing.T, name string) (*Stream, string) {
	t.Helper()
	root := t.TempDir()
	dir := filepath.Join(root, "docs", "streams", name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	return &Stream{Name: name, Dir: dir, Root: root}, root
}

// TestCoverage is the baseline: one Verify row with a matching, passing witness
// releases the brief with exactly one `pass` claim.
func TestCoverage(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "abc123def456"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c, ok := cov["cov/01"]
	if !ok {
		t.Fatalf("no coverage computed for cov/01 (got %+v)", cov)
	}
	if !c.Released {
		t.Fatalf("want released, got held: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covPass {
		t.Fatalf("want exactly one pass claim, got %+v", c.Claims)
	}
}

// TestCoverageWrongRevisionHolds — a witness whose recorded tree SHA differs
// from the item's revision is `wrong-revision`, and the brief is held, never
// released on the strength of a witness proven only for a different commit.
func TestCoverageWrongRevisionHolds(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "aaaaaaaaaaaa"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{Revision: "bbbbbbbbbbbb"})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a witness at the wrong revision must hold the brief, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covWrongRevision {
		t.Fatalf("want wrong-revision, got %+v", c.Claims)
	}
}

// TestCoverageCouldNotCheckIsNotPass — a `could-not-run` witness resolves
// `could-not-check` and holds; it must never be read as pass.
func TestCoverageCouldNotCheckIsNotPass(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", stateCouldNotRun, "abc123def456"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("could-not-run must never release the brief, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covCouldNotCheck {
		t.Fatalf("want could-not-check, got %+v", c.Claims)
	}
}

// TestCoverageJoinRequiresIntegrationRow — Task item 2: a brief bound to the
// pattern's join node needs at least one Verify row classed `+flow`;
// individually-passing site rows alone do not release the join. No adapter
// exists yet (this brief's integration amendment), so the binding and the
// parsed pattern are constructed directly here — exactly the
// "testable without a provider" the amendment asks for.
func TestCoverageJoinRequiresIntegrationRow(t *testing.T) {
	pat := patternDoc{
		Name: "fixture-pattern",
		Join: "verify",
		NodeByID: map[string]patternNode{
			"verify": {ID: "verify", Kind: "check", Role: "verifier"},
		},
	}
	opts := coverageOptions{
		Bindings: map[string]coverageBinding{"cov/01": {Pattern: "fixture-pattern", Node: "verify"}},
		Patterns: map[string]patternDoc{"fixture-pattern": pat},
	}

	// Site rows only (no +flow obligation) — held on integration-check.
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Class | Command | Expect |\n|---|-------|---------|--------|\n| 1 | check | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "abc123def456"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, opts)
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("individually-passing site rows must not release the join, got released: %+v", c)
	}
	foundMissingIntegration := false
	for _, cl := range c.Claims {
		if cl.Claim == "integration-check" && cl.Result == covMissing {
			foundMissingIntegration = true
		}
	}
	if !foundMissingIntegration {
		t.Fatalf("want a missing integration-check claim, got %+v", c.Claims)
	}

	// Add a +flow row — the join releases.
	s2, root2 := mustCoverageStream(t, "cov")
	verify2 := "| # | Class | Command | Expect |\n|---|-------|---------|--------|\n| 1 | check +flow | `true` | exit 0 |"
	ev2 := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "abc123def456"))
	writeCoverageBrief(t, s2.Dir, "01", "cov", verify2, ev2)

	cov2 := evaluateCoverage(root2, []*Stream{s2}, opts)
	c2 := cov2["cov/01"]
	if !c2.Released {
		t.Fatalf("a +flow row should release the join, got held: %+v", c2)
	}
}

// TestCoverageAdviceCannotSupplyWitness — 2026-09-18 integration amendment: "a
// model assessment is never an execution witness." Prose asserting confidence
// about a row — however emphatic — does not match verifyrun's own witness shape
// (an `exit=` marker AND a `sha256:` marker, each in its own cell), so it can
// never supply a missing mandatory claim.
func TestCoverageAdviceCannotSupplyWitness(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := "| # | Note |\n|---|------|\n| 1 | HIGH CONFIDENCE: this row passes based on a code read, no execution needed |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a model's prose advice must never supply a missing execution witness, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covMissing {
		t.Fatalf("want missing, got %+v", c.Claims)
	}
}

// TestCoverageAcceptanceDigestChanged — 2026-09-18 integration amendment:
// "applicable evidence must bind the exact subject and acceptance-definition
// digest." A witness recorded against a Verify row's PRIOR Command text no
// longer describes the row after that text changes — the witness's acceptance
// definition changed out from under it, and the claim resolves `error`, never
// `pass` on the strength of a witness for a different question.
func TestCoverageAcceptanceDigestChanged(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	// The witness was recorded for `true`; the Verify row now reads something else.
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true && echo changed` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "abc123def456"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a witness whose acceptance definition changed must not release, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covError {
		t.Fatalf("want error (stale acceptance-definition digest), got %+v", c.Claims)
	}
}

// TestCoverageResultVocabularyIsClosed pins Verify row 6's contract: the
// printed `result` field is always one of the six fixed values, whatever the
// input shape (bad table, missing brief, empty Evidence).
func TestCoverageResultVocabularyIsClosed(t *testing.T) {
	closed := map[string]bool{
		covPass: true, covFail: true, covMissing: true,
		covError: true, covCouldNotCheck: true, covWrongRevision: true,
	}
	s, root := mustCoverageStream(t, "cov")
	writeCoverageBrief(t, s.Dir, "01", "cov",
		"| # | Command | Expect |\n|---|---------|--------|\n| 1 | `false` | exit 0 |",
		coverageEvidenceTable(covWitnessRow("1", "false", stateFail, "abc123def456")))
	writeCoverageBrief(t, s.Dir, "02", "cov",
		"| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |",
		"") // no evidence at all -> missing

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	for id, c := range cov {
		for _, cl := range c.Claims {
			if !closed[cl.Result] {
				t.Errorf("%s: claim %q resolved to %q, outside the closed six-value vocabulary", id, cl.Claim, cl.Result)
			}
		}
	}
}
