package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// coverage_test.go — the evidence coverage rule (graph-execution/03). Top-level
// functions are named TestCoverage* so Verify row 1's `-run TestCoverage`
// selector counts them all.

// covWitnessRow renders one Evidence witness row exactly as verifyrun.go's own
// witness.row() would — generated by the SAME code coverage.go reads, never a
// hand-typed guess at the table format.
func covWitnessRow(id, command, state, tree string) string {
	exit := 0
	if state == stateFail {
		exit = 1
	}
	w := witness{
		ID: id, Command: command, State: state, Exit: exit,
		OutHash: "abc123def456", Date: "2026-09-25", Runner: "fixture-verifier", Tree: tree,
	}
	return w.row()
}

// coverageEvidenceTable wraps one or more witness/advice rows in the witness
// table header.
func coverageEvidenceTable(rows ...string) string {
	out := witnessHeader
	for _, r := range rows {
		out += "\n" + r
	}
	return out
}

// writeCoverageBrief writes a minimal, valid brief-v1 file (the same required-key
// shape testdata/autoflip's fixtures already use) with the given Verify/Evidence
// bodies, under dir/brief-<num>.md.
func writeCoverageBrief(t *testing.T, dir, num, streamName, verifyBody, evidenceBody string) {
	t.Helper()
	writeCoverageBriefWithFiles(t, dir, num, streamName, "", verifyBody, evidenceBody)
}

// writeCoverageBriefWithFiles is writeCoverageBrief plus an optional `## Context`
// `files:` line (filesLine is its inline value, e.g. "`src/impl.go`"; "" omits
// the Context section entirely) — the declared scope a witness speaks for
// (review finding F2, round 2).
func writeCoverageBriefWithFiles(t *testing.T, dir, num, streamName, filesLine, verifyBody, evidenceBody string) {
	t.Helper()
	context := ""
	if filesLine != "" {
		context = "## Context\nfiles: " + filesLine + "\n\n"
	}
	content := fmt.Sprintf(`---
brief: %s/%s
title: coverage fixture
wave: 0
depends: []
unblocks: []
effort: S
gate: model
risk: {regulatory: no, customer: no, irreversible: no, sensitive-data: no}
issues: []
schema: brief-v1
authored: 2026-09-25 by graph-execution/03 fixture
sources: ["fixture: graph-execution/03 coverage_test.go"]
---

# Brief %s — coverage fixture

%s## Verify
%s

## Evidence
<!-- contract comment -->

%s

## Review
Gate: model.
`, streamName, num, num, context, verifyBody, evidenceBody)
	if err := os.WriteFile(filepath.Join(dir, "brief-"+num+".md"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// mustCoverageStream returns a fresh temp root (deliberately NOT a git repo —
// currentTreeRevision(root) resolves "" there, so a test that cares about the
// revision comparison passes opts.Revision explicitly rather than depending on
// this session's own git state) plus one empty stream directory under it.
func mustCoverageStream(t *testing.T, name string) (*Stream, string) {
	t.Helper()
	root := t.TempDir()
	dir := filepath.Join(root, "docs", "streams", name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	return &Stream{Name: name, Dir: dir, Root: root}, root
}

// TestCoverage is the baseline: one Verify row with a matching, passing witness
// releases the brief with exactly one `pass` claim.
func TestCoverage(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	// The witness must be corroborable against real history (review finding F3,
	// round 2: an unreadable historical row is could-not-check, never pass), so
	// the brief's Verify row is committed first and the witness names that
	// commit — the in-progress shape: HEAD is still the tree the check ran on,
	// with only the Evidence write uncommitted on top.
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	witnessTree := mustGitInit(t, root)
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c, ok := cov["cov/01"]
	if !ok {
		t.Fatalf("no coverage computed for cov/01 (got %+v)", cov)
	}
	if !c.Released {
		t.Fatalf("want released, got held: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covPass {
		t.Fatalf("want exactly one pass claim, got %+v", c.Claims)
	}
}

// TestCoverageNoTargetRevisionIsCouldNotCheck — review finding F1, case 2: an
// unreadable/absent item revision must never default a witness to `pass`. A
// witness with a well-formed tree token, but no established target to compare
// it against, resolves `could-not-check`, not `pass`.
func TestCoverageNoTargetRevisionIsCouldNotCheck(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "abc123def456"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{}) // no Revision override; root has no git history
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("an unestablished item revision must never release the brief, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covCouldNotCheck {
		t.Fatalf("want could-not-check, got %+v", c.Claims)
	}
}

// TestCoverageMissingTreeTokenIsCouldNotCheck — review finding F1, case 1: a
// witness with NO tree token at all, against a KNOWN item revision, must never
// default to `pass` just because there was nothing to contradict it.
func TestCoverageMissingTreeTokenIsCouldNotCheck(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "")) // no @ tree token
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{Revision: "abc123def456"})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a witness with no tree token must never release against a known item revision, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covCouldNotCheck {
		t.Fatalf("want could-not-check, got %+v", c.Claims)
	}
}

// TestCoverageShortTreeTokenIsCouldNotCheck — review finding F1, case 3: a
// tree token shorter than minRevisionTokenLen must never be read as a match
// (a 1-character token matches roughly 1 in 16 real SHAs by coincidence).
func TestCoverageShortTreeTokenIsCouldNotCheck(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "a"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	// The target starts with the same single character, so the old
	// shortest-prefix comparison would have called this a match.
	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{Revision: "abc123def456"})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a 1-character tree token must never be read as a match, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covCouldNotCheck {
		t.Fatalf("want could-not-check, got %+v", c.Claims)
	}
}

// TestCoverageWrongRevisionHolds — a witness whose recorded tree SHA differs
// from the item's revision is `wrong-revision`, and the brief is held, never
// released on the strength of a witness proven only for a different commit.
func TestCoverageWrongRevisionHolds(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "aaaaaaaaaaaa"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{Revision: "bbbbbbbbbbbb"})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a witness at the wrong revision must hold the brief, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covWrongRevision {
		t.Fatalf("want wrong-revision, got %+v", c.Claims)
	}
}

// TestCoverageCouldNotCheckIsNotPass — a `could-not-run` witness resolves
// `could-not-check` and holds; it must never be read as pass.
func TestCoverageCouldNotCheckIsNotPass(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", stateCouldNotRun, "abc123def456"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("could-not-run must never release the brief, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covCouldNotCheck {
		t.Fatalf("want could-not-check, got %+v", c.Claims)
	}
}

// TestCoverageJoinRequiresIntegrationRow — Task item 2: a brief bound to the
// pattern's join node needs at least one Verify row classed `+flow`;
// individually-passing site rows alone do not release the join. No adapter
// exists yet (this brief's integration amendment), so the binding and the
// parsed pattern are constructed directly here — exactly the
// "testable without a provider" the amendment asks for.
func TestCoverageJoinRequiresIntegrationRow(t *testing.T) {
	pat := patternDoc{
		Name: "fixture-pattern",
		Join: "verify",
		NodeByID: map[string]patternNode{
			"verify": {ID: "verify", Kind: "check", Role: "verifier"},
		},
	}
	// Each fixture root is git-backed with the Verify row committed and the
	// witness naming that commit (see TestCoverage), so the only thing that can
	// hold these briefs is the join rule itself — not F1's unestablished-revision
	// handling nor F3's unreadable-history handling.
	opts := coverageOptions{
		Bindings: map[string]coverageBinding{"cov/01": {Pattern: "fixture-pattern", Node: "verify"}},
		Patterns: map[string]patternDoc{"fixture-pattern": pat},
	}

	// Site rows only (no +flow obligation) — held on integration-check.
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Class | Command | Expect |\n|---|-------|---------|--------|\n| 1 | check | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	w1 := mustGitInit(t, root)
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, w1))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, opts)
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("individually-passing site rows must not release the join, got released: %+v", c)
	}
	foundMissingIntegration := false
	for _, cl := range c.Claims {
		if cl.Claim == "integration-check" && cl.Result == covMissing {
			foundMissingIntegration = true
		}
	}
	if !foundMissingIntegration {
		t.Fatalf("want a missing integration-check claim, got %+v", c.Claims)
	}

	// Add a +flow row — the join releases.
	s2, root2 := mustCoverageStream(t, "cov")
	verify2 := "| # | Class | Command | Expect |\n|---|-------|---------|--------|\n| 1 | check +flow | `true` | exit 0 |"
	writeCoverageBrief(t, s2.Dir, "01", "cov", verify2, "")
	w2 := mustGitInit(t, root2)
	ev2 := coverageEvidenceTable(covWitnessRow("1", "true", statePass, w2))
	writeCoverageBrief(t, s2.Dir, "01", "cov", verify2, ev2)

	cov2 := evaluateCoverage(root2, []*Stream{s2}, opts)
	c2 := cov2["cov/01"]
	if !c2.Released {
		t.Fatalf("a +flow row should release the join, got held: %+v", c2)
	}
}

// TestCoverageAdviceCannotSupplyWitness — 2026-09-18 integration amendment: "a
// model assessment is never an execution witness." Prose asserting confidence
// about a row — however emphatic — does not match verifyrun's own witness shape
// (an `exit=` marker AND a `sha256:` marker, each in its own cell), so it can
// never supply a missing mandatory claim.
func TestCoverageAdviceCannotSupplyWitness(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	ev := "| # | Note |\n|---|------|\n| 1 | HIGH CONFIDENCE: this row passes based on a code read, no execution needed |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a model's prose advice must never supply a missing execution witness, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covMissing {
		t.Fatalf("want missing, got %+v", c.Claims)
	}
}

// TestCoverageAcceptanceDigestChanged — 2026-09-18 integration amendment:
// "applicable evidence must bind the exact subject and acceptance-definition
// digest." A witness recorded against a Verify row's PRIOR Command text no
// longer describes the row after that text changes — the witness's acceptance
// definition changed out from under it, and the claim resolves `error`, never
// `pass` on the strength of a witness for a different question.
func TestCoverageAcceptanceDigestChanged(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	// The witness was recorded for `true`; the Verify row now reads something else.
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true && echo changed` | exit 0 |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, "abc123def456"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a witness whose acceptance definition changed must not release, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covError {
		t.Fatalf("want error (stale acceptance-definition digest), got %+v", c.Claims)
	}
}

// TestCoverageResultVocabularyIsClosed pins Verify row 6's contract: the
// printed `result` field is always one of the six fixed values, whatever the
// input shape (bad table, missing brief, empty Evidence).
func TestCoverageResultVocabularyIsClosed(t *testing.T) {
	closed := map[string]bool{
		covPass: true, covFail: true, covMissing: true,
		covError: true, covCouldNotCheck: true, covWrongRevision: true,
	}
	s, root := mustCoverageStream(t, "cov")
	writeCoverageBrief(t, s.Dir, "01", "cov",
		"| # | Command | Expect |\n|---|---------|--------|\n| 1 | `false` | exit 0 |",
		coverageEvidenceTable(covWitnessRow("1", "false", stateFail, "abc123def456")))
	writeCoverageBrief(t, s.Dir, "02", "cov",
		"| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |",
		"") // no evidence at all -> missing

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	for id, c := range cov {
		for _, cl := range c.Claims {
			if !closed[cl.Result] {
				t.Errorf("%s: claim %q resolved to %q, outside the closed six-value vocabulary", id, cl.Claim, cl.Result)
			}
		}
	}
}

// ---------------------------------------------------------------------------
// git-backed fixtures — review findings F2 (ancestor revision matching) and F3
// (the Expect half of the acceptance-definition digest guard) need a REAL git
// checkout, unlike mustCoverageStream's deliberately non-git temp dir.
// ---------------------------------------------------------------------------

// mustGitHeadShort returns root's current HEAD SHA, truncated to treeSHALen —
// the same truncation currentTreeRevision/treeSHA already apply, so a witness
// stamped with this value compares like-for-like.
func mustGitHeadShort(t *testing.T, root string) string {
	t.Helper()
	out, err := exec.Command("git", "-C", root, "rev-parse", "HEAD").Output()
	if err != nil {
		t.Fatalf("git rev-parse HEAD: %v", err)
	}
	sha := strings.TrimSpace(string(out))
	if len(sha) > treeSHALen {
		sha = sha[:treeSHALen]
	}
	return sha
}

// mustGitInit turns root (already populated with fixture files) into a real
// git repo with everything on disk committed, and returns the resulting HEAD.
// The commit identity is a fixed, throwaway one (runGit is gitinfo_test.go's
// shared helper — `git -C` is never used here since that helper runs the
// command with cmd.Dir set instead), never the ambient user's.
func mustGitInit(t *testing.T, root string) string {
	t.Helper()
	runGit(t, root, "init", "-q")
	runGit(t, root, "config", "user.email", "fixture@example.com")
	runGit(t, root, "config", "user.name", "fixture")
	runGit(t, root, "config", "commit.gpgsign", "false")
	runGit(t, root, "add", "-A")
	runGit(t, root, "commit", "-q", "-m", "fixture: initial")
	return mustGitHeadShort(t, root)
}

// mustGitCommitAll commits every change currently on disk in an ALREADY-git
// root and returns the new HEAD.
func mustGitCommitAll(t *testing.T, root, message string) string {
	t.Helper()
	runGit(t, root, "add", "-A")
	runGit(t, root, "-c", "commit.gpgsign=false", "commit", "-q", "-m", message)
	return mustGitHeadShort(t, root)
}

// TestCoverageAncestorWitnessReleases — review finding F2: a witness is
// committed as PART OF the Evidence write that records it, so by the time
// anyone reads that Evidence, HEAD has already moved past the tree the
// witness ran on. Treating that as a plain mismatch would refuse EVERY real
// witness forever — the review's own reproduction: 287/287 briefs held, 0
// released, on this PR's own tree. classifyRevision must still release when
// the witness tree is an ancestor of HEAD and nothing but the brief's own
// file changed since (the ordinary "run the check, then commit the Evidence"
// shape).
func TestCoverageAncestorWitnessReleases(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "") // no Evidence yet — this is the tree the check ran against
	witnessTree := mustGitInit(t, root)

	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev) // the ONLY change: the brief's own Evidence
	head := mustGitCommitAll(t, root, "record Evidence")
	if head == witnessTree {
		t.Fatalf("the Evidence commit must move HEAD past the witness tree for this test to mean anything (both %s)", head)
	}

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if !c.Released {
		t.Fatalf("a witness tree that is an ancestor of HEAD, with only the brief's own file changed since, must release — got held: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covPass {
		t.Fatalf("want pass, got %+v", c.Claims)
	}
}

// TestCoverageAncestorWitnessOtherPathChangedMismatch — the F2 fix's other
// side: when something BESIDES the brief's own file changed after the witness
// ran, the witness no longer speaks for today's code, and coverage must still
// report `wrong-revision` rather than crediting the ancestor relationship
// alone. The brief declares no `files:` line, so the witness speaks for every
// path outside the board's own bookkeeping (round-2 F2 scope rule) — a change
// to an implementation path (src/, not docs/streams/** or STATUS.md) holds it.
func TestCoverageAncestorWitnessOtherPathChangedMismatch(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	if err := os.MkdirAll(filepath.Join(root, "src"), 0o755); err != nil {
		t.Fatal(err)
	}
	other := filepath.Join(root, "src", "other.txt")
	if err := os.WriteFile(other, []byte("v1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	witnessTree := mustGitInit(t, root)

	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)
	if err := os.WriteFile(other, []byte("v2\n"), 0o644); err != nil { // real implementation change, not just Evidence
		t.Fatal(err)
	}
	mustGitCommitAll(t, root, "record Evidence and change other.txt")

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("a real change to another path after the witness ran must still hold the brief, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covWrongRevision {
		t.Fatalf("want wrong-revision, got %+v", c.Claims)
	}
}

// TestCoverageExpectChangedSinceWitnessRan — review finding F3: an Expect-only
// tightening after the witness ran is invisible to the Command-text guard
// alone. classifyRevision here resolves a match (only the brief's own file
// changed, same as TestCoverageAncestorWitnessReleases), so this pins that the
// SEPARATE Expect-history guard (verifyRowAtRevision) still catches it.
func TestCoverageExpectChangedSinceWitnessRan(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	witnessTree := mustGitInit(t, root)

	verifyTightened := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0; output contains READY |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
	writeCoverageBrief(t, s.Dir, "01", "cov", verifyTightened, ev)
	mustGitCommitAll(t, root, "tighten Expect and record Evidence")

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	c := cov["cov/01"]
	if c.Released {
		t.Fatalf("an Expect change since the witness ran must never release on the strength of a witness for a different question, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covError {
		t.Fatalf("want error (stale acceptance-definition digest), got %+v", c.Claims)
	}
}

// ---------------------------------------------------------------------------
// Round-2 review (head e43403dfd): F2 — the witness scope; F3 — the Expect
// guard must never be skipped into a `pass`; S3/A5 — the declared `+dirty`
// tolerance.
// ---------------------------------------------------------------------------

// mustWriteFile writes content to root/rel, creating parent directories.
func mustWriteFile(t *testing.T, root, rel, content string) {
	t.Helper()
	p := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestCoverageDirtyWitnessExpectChangedIsError — round-2 F3(a) / security S1
// (the review's PROBE-F): a witness recorded over an uncommitted tree carries
// `@ <sha>+dirty`, the ordinary verifyrun shape. The Expect-history guard must
// read the row at the witness's BASE commit (suffix stripped) and still catch
// an Expect tightened after the run — never skip itself into a `pass`.
func TestCoverageDirtyWitnessExpectChangedIsError(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	witnessTree := mustGitInit(t, root)

	verifyTightened := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0; output contains READY |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree+"+dirty"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verifyTightened, ev)
	mustGitCommitAll(t, root, "tighten Expect and record a +dirty witness")

	c := evaluateCoverage(root, []*Stream{s}, coverageOptions{})["cov/01"]
	if c.Released {
		t.Fatalf("a +dirty witness must not skip the Expect guard into a release, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covError {
		t.Fatalf("want error (stale acceptance-definition digest), got %+v", c.Claims)
	}
}

// TestCoverageBriefAbsentAtWitnessTreeIsCouldNotCheck — round-2 F3(b) / security
// S2 (PROBE-G): the brief did not exist at the witness's tree (first committed
// together with its Evidence), so the row the witness answered cannot be read.
// That is could-not-check — uncorroborated is never `pass`.
func TestCoverageBriefAbsentAtWitnessTreeIsCouldNotCheck(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	mustWriteFile(t, root, "src/impl.txt", "v1\n")
	witnessTree := mustGitInit(t, root) // the brief is NOT in this tree

	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0; output contains READY |"
	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)
	mustGitCommitAll(t, root, "add the brief together with its Evidence")

	c := evaluateCoverage(root, []*Stream{s}, coverageOptions{})["cov/01"]
	if c.Released {
		t.Fatalf("a witness whose Verify row cannot be read at its own tree must never release, got released: %+v", c)
	}
	if len(c.Claims) != 1 || c.Claims[0].Result != covCouldNotCheck {
		t.Fatalf("want could-not-check, got %+v", c.Claims)
	}
}

// TestCoverageRowAbsentAtWitnessTreeIsCouldNotCheck — round-2 F3(b): the brief
// existed at the witness's tree, but the row id did not (it was added after).
func TestCoverageRowAbsentAtWitnessTreeIsCouldNotCheck(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	writeCoverageBrief(t, s.Dir, "01", "cov", "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |", "")
	witnessTree := mustGitInit(t, root)

	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |\n| 2 | `true` | exit 0 |"
	ev := coverageEvidenceTable(
		covWitnessRow("1", "true", statePass, witnessTree),
		covWitnessRow("2", "true", statePass, witnessTree),
	)
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)
	mustGitCommitAll(t, root, "add row 2 and record Evidence for both")

	c := evaluateCoverage(root, []*Stream{s}, coverageOptions{})["cov/01"]
	if c.Released {
		t.Fatalf("row 2 did not exist at the witness's tree, so the brief must not release, got released: %+v", c)
	}
	got := map[string]string{}
	for _, cl := range c.Claims {
		got[cl.Claim] = cl.Result
	}
	if got["Verify row #1: true"] != covPass || got["Verify row #2: true"] != covCouldNotCheck {
		t.Fatalf("want row 1 pass, row 2 could-not-check; got %+v", c.Claims)
	}
}

// TestCoverageSiblingEvidenceAndStatusRegenStillRelease — round-2 F2 (PROBE-D
// and PROBE-E): the model-lane flip runs at the main tip, and between the
// witness tree and that tip a verify batch lands Evidence for SEVERAL briefs in
// one commit and statusgen regenerates STATUS.md after every push. That board
// bookkeeping is not something the witness speaks for; it must not turn a
// witness into `wrong-revision`.
func TestCoverageSiblingEvidenceAndStatusRegenStillRelease(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	writeCoverageBrief(t, s.Dir, "02", "cov", verify, "")
	mustWriteFile(t, root, "STATUS.md", "board v1\n")
	witnessTree := mustGitInit(t, root)

	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)
	writeCoverageBrief(t, s.Dir, "02", "cov", verify, ev) // sibling brief's Evidence, same batch commit
	mustWriteFile(t, root, "docs/streams/verify-outcomes.jsonl", "{}\n")
	mustGitCommitAll(t, root, "verify batch: Evidence for 01 and 02")
	mustWriteFile(t, root, "STATUS.md", "board v2\n")
	mustGitCommitAll(t, root, "chore(status): regenerate")

	cov := evaluateCoverage(root, []*Stream{s}, coverageOptions{})
	for _, id := range []string{"cov/01", "cov/02"} {
		c := cov[id]
		if !c.Released || len(c.Claims) != 1 || c.Claims[0].Result != covPass {
			t.Fatalf("%s: sibling Evidence plus a STATUS.md regen must not invalidate the witness, got %+v", id, c)
		}
	}
}

// TestCoverageDeclaredFilesScopeTheWitness — round-2 F2: when the brief
// declares `files:`, those paths are what the witness speaks for. A change to
// an undeclared implementation path after the witness ran releases; a change
// to a declared path (including one under a declared directory) holds.
func TestCoverageDeclaredFilesScopeTheWitness(t *testing.T) {
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	files := "`src/impl.go`, `src/pkg/` (planned)"
	cases := []struct {
		name    string
		changed string
		want    string
	}{
		{"undeclared path changed releases", "src/unrelated.go", covPass},
		{"declared file changed holds", "src/impl.go", covWrongRevision},
		{"path under a declared directory holds", "src/pkg/inner.go", covWrongRevision},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			s, root := mustCoverageStream(t, "cov")
			writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", files, verify, "")
			mustWriteFile(t, root, tc.changed, "v1\n")
			witnessTree := mustGitInit(t, root)

			ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree))
			writeCoverageBriefWithFiles(t, s.Dir, "01", "cov", files, verify, ev)
			mustWriteFile(t, root, tc.changed, "v2\n")
			mustGitCommitAll(t, root, "record Evidence; change "+tc.changed)

			c := evaluateCoverage(root, []*Stream{s}, coverageOptions{})["cov/01"]
			if len(c.Claims) != 1 || c.Claims[0].Result != tc.want {
				t.Fatalf("changed %s: want %s, got %+v", tc.changed, tc.want, c.Claims)
			}
		})
	}
}

// TestCoverageDirtyWitnessToleranceIsDeclared pins the round-2 S3/A5 decision
// (coverage.go header, "THE +dirty TOLERANCE"): a `+dirty` witness is compared
// by its base commit, on both the exact and the ancestor path, and every other
// guard still binds. This is a DELIBERATE, documented tolerance — if it is ever
// narrowed, this test is the one to change, in the same commit as the spec.
func TestCoverageDirtyWitnessToleranceIsDeclared(t *testing.T) {
	s, root := mustCoverageStream(t, "cov")
	verify := "| # | Command | Expect |\n|---|---------|--------|\n| 1 | `true` | exit 0 |"
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, "")
	witnessTree := mustGitInit(t, root)

	ev := coverageEvidenceTable(covWitnessRow("1", "true", statePass, witnessTree+"+dirty"))
	writeCoverageBrief(t, s.Dir, "01", "cov", verify, ev)
	mustGitCommitAll(t, root, "record a +dirty witness")

	c := evaluateCoverage(root, []*Stream{s}, coverageOptions{})["cov/01"]
	if !c.Released || len(c.Claims) != 1 || c.Claims[0].Result != covPass {
		t.Fatalf("the declared +dirty tolerance: want pass at the base commit, got %+v", c)
	}
}
